### ISSUE TITLE
한국서버 접속 안됨.

### ISSUE THREAD

**Issue by dcmichael** [mrz1277/LoLKR#1]
오늘 LoL을 처음 설치해서, 북미서버 업데이트를 완료 한뒤 바로 LoLKR을 실행했습니다.
그랬더니 북미 상태일때는 이렇게 launch버튼이 나타나지만
![2015-04-20 01 52 09](https://cloud.githubusercontent.com/assets/3986581/7220393/038faf22-e700-11e4-9359-17b6ac50bc40.png)
한국서버로 변경을 하니 아래와 같은 에러가 발생하네요.
![2015-04-20 01 52 46](https://cloud.githubusercontent.com/assets/3986581/7220392/038f90c8-e700-11e4-9ed4-bea5fa3c275e.png)
![2015-04-20 01 52 30](https://cloud.githubusercontent.com/assets/3986581/7220391/03881b68-e700-11e4-9385-e9c3d7f1af1f.png)

해당 문제 발생시의 LoL의 로그입니다.
https://drive.google.com/file/d/0B3qAs7Oq71RbbG1FLURxZGoydnc/view?usp=sharing

**Comment by mrz1277** [comment]
로그를 보니 `/Users/dcmichael/Library/Application Support/Riot Games/machine.cfg` 파일을 읽을 수 없다는데 해당 경로에 혹시 파일이 존재하는지 확인해보세요. 그리고 북미섭을 선택한 뒤 종료하시고 '패치하기'를 실행하시면 롤을 다시 실행하실때 한국서버로 자동 선택되는데 이렇게도 한번 테스트 해보시겠어요?

**Comment by mrz1277** [comment]
https://github.com/mrz1277/LoLKR/issues/4 참고
