### ISSUE TITLE
도와주시길 바랍니다 

### ISSUE THREAD

**Issue by Hanchoa** [mrz1277/LoLKR#10]
![screen shot 2015-05-16 at 6 42 08 pm](https://cloud.githubusercontent.com/assets/12472237/7665983/4a6da25e-fbfb-11e4-8b26-f235b3d7f0d4.png)

이렇게 뜨는데 어떻게하죠 ㅠㅠ

**Comment by ghost** [comment]
관리자 비밀번호 입력하시면 됩니다.

**Comment by Hanchoa** [comment]
혹시 스카이프 있으신지요.. 도움이필요해서요

**Comment by ghost** [comment]
네 있습니다!

**Comment by ghost** [comment]
저도 같은 상황입니다. 
password를 입력하라고 뜨는데 키보드가 먹통입니다.
자신의 맥북 password 를 입력하라는 건지 아니면, 프로그램의 password를 입력하라는 건지 모르겠구요.
일단, password가 입력조차 안됩니다. 키보드가 그냥 먹통상태이고 enter만 쳐집니다.
brew 를 다운받으면 Hanchoa 님의 상황이 발생하고 그뒤엔 nginx 설치도 불가합니다.
이럴경우 어떻게 해야되나요?

**Comment by mrz1277** [comment]
패스워드 입력이 안되는것처럼 보이지만 실제론 입력을 받고 있는 상태입니다. 비밀번호는 부팅후 로그인되는 비밀번호 입니다.

**Comment by ghost** [comment]
오, 확실히 설치가 되는군요.
password 라는건 맥북 관리자 비밀번호네요. (혹시, 다른 분들을 위해서 글을 남깁니다.)
1. 터미널에 brew 명령어를 실행후에 입력하라는 password 는 투명으로 나와서 "입력이 안되는 것처럼 보이지만, 실제론 입력을 받고 있는 상태"이었어요.
2. 그래서 brew 를 설치하고, "패치하기"버튼을 다시 누르고 nginx 를 설치하였습니다.
3. nginx 설치가 시작되었을적에 프로그램 설치 명령어가 네모칸에 쭈욱 나오면서 옆에 스크롤이 뜨는데, 사용자가 스크롤을 따라 내리면 절대 안돼고 설치가 끝났다는 말이 나올때까지 그냥 놔두세요. 모래시계가 돌아가며 먹통이 됩니다. 강제종료하고 다시 실행 시키셔야 되요. 그러니 설치 명령어를 보기위해 스크롤은 절대 건들지 마시고 그냥 설치가 끝마칠때까지 가만히 놔두시면 됩니다. 
4. 마지막으로 롤을 다시 실행시키시고 게임을 즐기시면 됩니다. 

마지막으로 딱 한가지더!
지금이 2015년 5월 17일 일요일,
현재 북미서버가 5.9 버전 
한국서버가 5.8 버전입니다.
이미 사용자의 클라이언트가 북미서버 5.9버전이라면 지금 이걸 설치하고 5.8버전의 한국서버를 플레이할수 없습니다.
지금 아무리 재설치를 한다하여도 일단은 북미는 이미 5.9버전이기에 재설치해도 의미가 없다는 뜻인가요?
5.9버전에서 6.0버전으로 넘어갈때부터 이 프로그램의 사용의미가 있다는 것인지?

**Comment by ghost** [comment]
제작자님의 프로그램 기본 로직은 이해가 가는데, 롤 서버버전에 따른 사용법에서 명확하게 어떤상황에서는 되고 안되고가 조금 불분명해서 적어본 글이었습니다.

**Comment by mrz1277** [comment]
@kevinklim 님께서 잘 정리해주셨습니다. 저도 이번 패치때 많은 분들이 헷갈려 하시는걸 보고 설명 페이지를 좀더 보완하고 있습니다.. 마지막부분 답변해드리자면, 지금 시기에 롤 재설치는 소용이 없는게 맞고, 기존 5.8대에서 본 패치를 하신분들만 현재 한국서버에 접속할 수 있습니다. 따라서 이번 5.9때 패치하신분들은 5.9에서 5.10으로 넘어갈때 정상적으로 이용하실 수 있습니다.

**Comment by ghost** [comment]
답변 고맙습니다.
제가 이해력이 조금 부족한건지 아니면 혼자 혼란스러운건지 모르겠지만, 몇가지 더 궁금증이 남습니다.
(이거이거... 제가 너무 어렵게 이해하는 건지 모르겠네요. 나 바본가...)

제작하신 프로그램은 한국서버가 5.8v 이고 북미서버가 5.8v, 즉 두 서버가 같은 #의 버전일 때,
이 프로그램을 통해서 "강제로" 로컬한국서버(5.8v)을 북미서버의 자동업데이트(5.9v)로부터 묶어두고(지연시킨다는 표현이 맞겠네요) 5.8v로 그대로 남겨두는 기본로직인것 같은데... 

만약,
아직 북미서버(5.9v) 로 업데이트되지 않은 5.8 버전 클라이언트를 가지고 있습니다. 이럴경우, 서로 버전이 다른 북미서버(5.9v)과 한국서버(5.8v)을 제작하신 프로그램 LOL.KR을 통해서 동시에 오갈수 있는 건가요? 
아니면, 자동업데이트가 불가능하니, 한국서버 5.8v만 계속 접속가능하고, 한국서버가 다음번 5.9v으로 정식 업데이트가 되기 전까지는 북미서버에 접속이 불가능하다는 것인지?
(로컬을 바꾸는거라서 클라이언트랑은 상관이 없나요...?)
1. 또 다른 해결책?!
   전 댓글에서 암시드렸다시피, Mac에서 LOL을 실행시키려면 일단 북미서버 클라이언트를 필수불가결 요소로 실행시켜야 합니다. 그러면 자동적으로 업데이트가 되겠죠. 5.9v 으로 됩니다.
   이게 자체 클라이언트를 가진 게임의 한계네요. 모든 설치파일을 맨처음 설치시 웹서버에서 가지고와야하는 로컬설정이 되어 있어서... 아니면 lol_install.dmg 파일안의 로컬설정을 한국서버로 임의로 프로그래밍에서 수정하면 아예 처음설치시 한국서버에서 설치파일을 불러오는건 아닐런지.. (만약 말처럼 이게 된다면, 이미 맥용 한국서버 롤이 되었을텐데 말이죠.)
   솔직히 다른게임은 설치와 업데이트를 동시에 하지않으니까, 설치후에 안의 파일을 수정해주면 될것같은 논리인데.
   LOL은 클라이언트를 통해서 설치와 업데이트가 동시에 이루어지는 것 같아서 중간단계에서 설치파일을 수정불가한거 같고요.
   제가 프로그래머가 아닌 일반사용자라서 일단 좀 끄적여 보았습니다만, 제가 횡설수설하는건 아닌지 모르겠네요.
   읽어보시기에도 말이 안돼죠? ㅋㅋㅋ

**Comment by mrz1277** [comment]
1. 본문 내용 중간에 보면 북미(5.9)와 한국(5.8)서버 번갈아가며 접속하는 스크린샷 있으니 참고하시면 됩니다. 가상 한국 서버는 다른 지역과 독립적으로 작동하기 때문에 미리 패치만 되어있으면 지역간 버전 차이가 나도 서로 접속할 수 있습니다.
2. 사실 처음 설치하는 사용자든지 미리 북미용 버전으로 업데이트가 된 사용자든지 한국서버 버전에 맞게 접속하는 방법이 없는것은 아닙니다. 로컬에서 업데이트 서버를 두지 않고 자체 업데이트 서버를 웹상에 두고 로컬에 다운받은 메타파일들을 그곳에 호스팅 하면 됩니다. 저도 처음엔 이 방법으로 할까 고민했으나, 무료로 배포되는 솔루션으로 호스팅 비용을 부담하거나 관리할 자신은 없었습니다. 이부분은 라이엇코리아에서 해야할 일이지요. :)

**Comment by ghost** [comment]
현재 2015년 6월 24일 8시 16분입니다.
북미서버 5.12
한국서버 5.11 입니다.
이미 방지프로그램 lolkr 이 작동중이었음에도 불구하고, 클라이언트가 북미서버에 맞춰 5.11에서 5.12로 업데이트 되었습니다. 
해당 프로그램의 이용효력이 없는 것인지에 대한 의구심이 듭니다.
5.12로 업데이트 후, 한국서버 5.11로의 로그인진입이 블럭 되었습니다.

**Comment by mrz1277** [comment]
터미널에 아래 커맨드를 한번 입력한후 출력값을 코멘트 해주세요.

```
cat "/Applications/League of Legends.app/Contents/LoL/RADS/system/system.cfg"
```

**Comment by ghost** [comment]
DownloadPath = /releases/Maclive
    DownloadURL = 127.0.0.1:8010
    Region = KR

**Comment by mrz1277** [comment]
저 상태라면 한국서버는 업데이트가 되지 않는게 맞는데, 어떤 이유로 업데이트가 됐는지 알 수가 없네요.
한국서버 5.12 업데이트 때부터는 롤을 클린 설치하시고 다시 한글패치 한다음 사용하셔야 할 것 같습니다.

**Comment by ghost** [comment]
게임클라이언트를 실행시킬때, 항상 LOLKR 앱을 실행시켜야 하는건지 아니면, 종료해도 상관없는건가요.
일단 방지탭을 오른쪽으로 되어 있어서 업데이트 방지는 되어있고, ngnix도 On 입니다만...

처음에, 클라이언트를 실행시켰을때, 갑자기 인터페이스 업데이트라며 5.12 버전으로의 업데이트가 바로 실행되더군요.
행여나 LOLKR을 실행시키고 클라이언트를 오픈했어야 하는 후회심도 들기도 합니다만. 제 잘못이었는지 아닌가 하는..

**Comment by ghost** [comment]
덧: 업데이트 허용 차단 설정을 변경할 때마다 '패치 하기' 버튼을 다시 눌러줘야 한다고 하니 이점 숙지하세요!

아마 이걸 제가 지키지 안아서 그런건지...

**Comment by mrz1277** [comment]
아.. 저거 혹시 블로그에서 보신 내용이라면... ㅠㅠ
원님께 말씀드려서 지워달라고 해야겠네요..
여기 본문 읽다보면 업데이트 기간엔 패치하기 버튼을 누르면 안된다고 적어놨는데,
패치하기 버튼은 특별한 상황이 아니면 최초에 한번만 해주시면 됩니다.

이거 @kevinklim 님만 난감하게 됐군요.ㅠㅠ

**Comment by ghost** [comment]
아니요, 저도 최초 설치시 패치 한번 하고 그 이후론 안했어요.
혹시나 매번 패치를 안해서 이러한 일이 일어났나 했는데, 오히려 아니라고 하시니...
갈피를 못잡겠네요. 다음에 클라이언트 업데이트 할때 다시한번 글 남길께요. 일단 클린 설치중입니다.
답변 고맙습니다.

**Comment by mrz1277** [comment]
@kevinklim 아, 참고로 lolkr 앱은 업데이트 때만 사용하시면 됩니다.

**Comment by doyoung9305** [comment]
<img width="582" alt="2015-07-10 1 58 44" src="https://cloud.githubusercontent.com/assets/13267993/8612468/fe1031ce-270b-11e5-9a6a-cd491e6c41af.png">
계속 이렇게 뜨는데 저는 어떻게 해결할수있나요 ㅠㅠ
소프트웨어 설치창은 한번뜨고 완료라고 한이후에는 다시 안뜨고 계속 저상태로 반복이네요.
비밀번호 입력한적도없구요..

**Comment by mrz1277** [comment]
Press ... 부분에서 엔터키를 입력해도 그러신가요?

**Comment by doyoung9305** [comment]
네 엔터키를 누르면 보시다시피 스크립트가 아예 사라져요.

**Comment by mrz1277** [comment]
혹시 사용하고 계신 OS X 버전이 어떻게 되실까요?
OS X 10.11(엘캐피탄) 이하라면 아래 커맨드를 터미널창에 입력해보세요.

```
xcode-select --install
```
