### ISSUE TITLE
7.5패치 이후 명시되지 않은 오류가 뜨는데요.

### ISSUE THREAD

**Issue by leejh0308** [mrz1277/LoLKR#103]
롤 재설치를 해보아도 그대로네요 해결책을 알 수 있을까요?

**Comment by rimichoi** [comment]
한글패치는 안되고요. LoLKR을 실행하고 nginx 초록불확인하고 허용으로 옮기고 /Applications/League of Legends.app/Contents/LoL/RADS/system 의 locale.cfg 의 언어를 en_AU로 변경하고 게임실행하시면 됩니다.

**Comment by Rested** [comment]
@berryzed  한국어 패치는 언제쯤있을 것으로 생각하십니까?
