### ISSUE TITLE
Can't download the software because of a network problem

### ISSUE THREAD

**Issue by Hanchoa** [mrz1277/LoLKR#11]
![screen shot 2015-05-16 at 6 55 33 pm](https://cloud.githubusercontent.com/assets/12472237/7666041/282219da-fbfd-11e4-99d3-b9a97f9ea6dd.png)

하.. 이건 또 왜그러는건가요 ㅠㅠ 와이파이는 잘만돌아가는데

**Comment by mrz1277** [comment]
맥 소프트웨어 업데이트 문제는 본 프로젝트의 이슈에 해당하지 않으므로 닫도록 하겠습니다..
