### ISSUE TITLE
 업데이트 방지하고 하였는데 접속이 안됩니다

### ISSUE THREAD

**Issue by ChoiMinJe** [mrz1277/LoLKR#12]
![2015-05-17 1 22 53](https://cloud.githubusercontent.com/assets/12474829/7666945/4a46055e-fc33-11e4-833c-4aa728abd1c8.png)
![2015-05-17 1 23 04](https://cloud.githubusercontent.com/assets/12474829/7666946/4a64d024-fc33-11e4-953f-2d98d081f948.png)
![2015-05-17 1 24 24](https://cloud.githubusercontent.com/assets/12474829/7666952/8b9e2630-fc33-11e4-8bc7-0d0cab8155d3.png)

어째서인지 또다시 안되내여 
첫번째 스크린샷에서 아래쪽에 있는 "이미 설치되어 있으므로 설치하지 않습니다." 이걸 선택하고 했어야 하나요?
그리고 nginx에 녹색불이 들어오지 않은 상태에서 롤을 실행시켜버려서 업데이트 된건가여? 
다시 프로그램을 켜보니 녹색불이 들어와있고 북미서버:5.9   한국서버:5.8이라고 되어있내여 ㅜㅜ 이상태에서 롤을 실행 시켰어야 했는게 맞나여? ㅜㅜ
이렇게 된이상 한국에서 5.9업데이트 해줄때까지 기다려야 겠내여

**Comment by mrz1277** [comment]
롤이 5.9로 업데이트가 되기전에 `LoLKR` 로 미리 패치가 되어있는 상태여야 합니다.
안타깝지만 이번엔 한국에서 5.9패치가 될때까지 기다리셔야 하고, 다음 패치기간때는 정상적으로 이용가능하실거에요.
