### ISSUE TITLE
도와주십시오

### ISSUE THREAD

**Issue by tec4322** [mrz1277/LoLKR#13]
북미서 맥용 롤을 다운받은후 패치완료후에 앱으로 패치하기까지 모두 완료했다.

롤을 다시실행시킨후 실행시켜보니 바드가 뜨는군요 ㅠㅠㅠ 5.9패치가 된 상태라 접속도 안되구요

해결방법이나 문제가 뭔지 알수 있는지요

**Comment by mrz1277** [comment]
본 솔루션은 한국 서버가 업데이트 되기전에 미리 패치해놓고 있어야 북미와 버전 차이가 나는 동안 정상적으로 접속이 가능합니다. 예를 들어 현재 한국 서버 버전은 아직 5.8인데 롤을 실행하여 5.9로 업데이트 되었다면 아래 앱을 설치한다고 해서 다시 5.8로 접속할 수는 없습니다. 이점 유의해 주세요.

**Comment by tec4322** [comment]
그럼 다음 한국서버의 5.9패치가 있을때 까지는 소용이 없는건가요?

**Comment by mrz1277** [comment]
네 이번패치때는 기다리셔야 합니다;; 다음 패치기간부터 정상적으로 이용하실 수 있습니다
