### ISSUE TITLE
도와주세유ㅠ

### ISSUE THREAD

**Issue by artists2** [mrz1277/LoLKR#14]
-

**Comment by mrz1277** [comment]
[명시되지않은오류](https://github.com/mrz1277/LoLKR#%EB%AA%85%EC%8B%9C%EB%90%98%EC%A7%80-%EC%95%8A%EC%9D%80-%EC%98%A4%EB%A5%98%EA%B0%80-%EB%B0%9C%EC%83%9D%ED%96%88%EB%8B%A4%EB%A9%B0-%EB%A1%A4%EC%9D%B4-%EC%8B%A4%ED%96%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)

[클라거부](https://github.com/mrz1277/LoLKR#%EB%AA%85%EC%8B%9C%EB%90%98%EC%A7%80-%EC%95%8A%EC%9D%80-%EC%98%A4%EB%A5%98%EA%B0%80-%EB%B0%9C%EC%83%9D%ED%96%88%EB%8B%A4%EB%A9%B0-%EB%A1%A4%EC%9D%B4-%EC%8B%A4%ED%96%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4)

**Comment by artists2** [comment]
네? 읽어봤는데 잘 모르겠어요ㅠㅠ 순서를 알려주실수?

**Comment by mrz1277** [comment]
명시되지 않은 오류 문제는 nginx가 켜지지 않아서 발생한 문제고,
클라거부는 문제는 현재 북미와 한국 서버간의 차이가 난 상태에서 롤을 새로 설치하면 이미 5.9버전으로 업그레이드가 되어버렸기 때문에 패치를 한다할지라도 5.8버전으로 접속할 수 없습니다. 이번 업데이트는 한국서버가 5.9로 업데이트 될때까지 기다리셔야하고, 이 다음 업데이트(5.10)때부터 정상적으로 이용하실 수 있습니다.

**Comment by artists2** [comment]
그렇군요 감사합니다
