### ISSUE TITLE
설치하고 나니까 핑이 터지네요...

### ISSUE THREAD

**Issue by joon15** [mrz1277/LoLKR#15]
요번에 깔아서 5.9 패치를 받았고 실행을 했습니다만...평소에는 30 정도 하던 핑이 설치후 갑자기 250 정도로 올라갔습니다. 이거 어떻게 해결해야 되나요. 
nginx에도 초록볼 들어오고 다 좋은데...
(인터넷 연결 이상 없고요, 중국이지만 광랜입니다)

**Comment by mrz1277** [comment]
패치는 업데이트때 서버 접속 경로를 우회하는 수단이기 때문에 인게임 핑과는 무관합니다. 핑은 롤 중계서버와 @joon15 님 컴퓨터간의 네트워크 (지연)속도와 관련이 있기 때문에 `activity monitor` 앱을 켜시고 `network` 부분을 모니터링 하면서 다른 프로세스가 점유하고 있는건 않은지 확인해 보세요. 그리고 원래 본인의 회선에 맞는 인터넷 속도(bps)가 보장되고 있는지 검사해보시기 바랍니다.

**Comment by joon15** [comment]
빠르고 좋은 답변 감사합니다
