### ISSUE TITLE
사진으로 질문드립니다

### ISSUE THREAD

**Issue by Hanchoa** [mrz1277/LoLKR#16]
사진많아도 이해해주세요 ㅎㅎ;

![screen shot 2015-05-23 at 4 49 58 pm](https://cloud.githubusercontent.com/assets/12472237/7783532/cb9e4396-016f-11e5-9f69-88e1de674d0e.png)
패치하기를 눌럿습니다

![screen shot 2015-05-23 at 4 50 02 pm](https://cloud.githubusercontent.com/assets/12472237/7783533/d4e8f9fa-016f-11e5-9d15-ae17131886bc.png)
그다음
![screen shot 2015-05-23 at 4 50 07 pm](https://cloud.githubusercontent.com/assets/12472237/7783536/e0b75074-016f-11e5-939b-d2465bf357ec.png)

이게 갑자기 뜨지만이런걸 받으란말은 없어서 건너뛰엇습니다

![screen shot 2015-05-23 at 4 50 59 pm](https://cloud.githubusercontent.com/assets/12472237/7783543/f619b362-016f-11e5-8677-1825fc5ca0e9.png)

관리자 비밀번호를 쳣습니다 

![screen shot 2015-05-23 at 4 52 57 pm](https://cloud.githubusercontent.com/assets/12472237/7783549/05ad4fb4-0170-11e5-8dd4-9f821176bdb0.png)

brew help to get started란말이 뜨는데 brew help를 쳐도 아무것도 안됩니다 LOLKR 어플에서는 nginx에 불도 안들어와잇고요 제가 바본거도 잇지만 좀 설명해주세요 ㅎㅎ

**Comment by mrz1277** [comment]
저 상태에서 다시 패치하기 해보셨나요? 그리고 중간에 설치하라는 팝업 뜨면 다 설치해주시는게 좋습니다.

**Comment by Hanchoa** [comment]
전에 올렷듯이 팝업을 설치하면 와이파이 문제잇다면서 안됩니다;;

**Comment by mrz1277** [comment]
와이파이 문제가 있다고 설치가 안되는 프로그램 이름이 어떤건가요?

**Comment by mrz1277** [comment]
추가 코멘트가 없어 임시적으로 본 이슈를 닫습니다.

**Comment by casseopea2** [comment]
내가 나중에 독단적 인 OS X 10.9보다 나중에 업데이 트하고 싶지 않았어 어쩌면 내가 선택의 여지가 없을거야
