### ISSUE TITLE
북미 5.10   한국5.9

### ISSUE THREAD

**Issue by ChoiMinJe** [mrz1277/LoLKR#17]
일단 오늘 컴을키고 순서를 말씀드릴께여
1.롤을 실행하니 "명시되지 않는 오류"라고 뜨면서 롤이 실행되지 않았습니다.
2.LOLKR을 실행 했습니다 nginx에 녹색불이 들어와있지 않았습니다.
3.그래서 패치하기를 하니깐 nginx에 녹색불이들어오고    북미5.10  한국5.9
nginx에 녹색불이 들어왔습니다. 이때 한국 서버 업데이트 또한 방지 되어있었는데
롤을 실행하니 북미가 5.10 업데이트가 됩니다..ㅜㅜ 왜 이런걸까여
또 다시 한국 업데이트를 기다려야 겠내여
제가 롤을 실행 하기전에 잘못 한게 있나여? ㅠㅠ

**Comment by mrz1277** [comment]
명시되지않은 오류는 nginx만 재실행하면 되는데 패치기간에 '패치하기'를 진행하시면 업데이트가 진행되게 됩니다.
문서를 보니 nginx를 재실행하기 위해 패치하기를 진행해도 된다는 부분이 있군요. 이부분은 패치기간엔 적용되지 않는 부분인데 수정해야겠습니다. 저도 테스트해보진 않아서 정확히 동작하는지 모르겠지만 [링크파일](https://dl.dropboxusercontent.com/u/9150331/releases_5.9.zip)을 다운받아 `/usr/local/var/www` 경로 아래 있는 기존 releases 폴더를 지우고 이동해보세요. 그리고 패치가 다시 5.9로 돌아가는지 보고 안된다면 내일 새벽 업데이트가 될때까지 기다리셔야 합니다.(ㅠㅠ)

**Comment by ChoiMinJe** [comment]
/usr/local/var/www 가 무슨 경로인지 잘모르겠내요 ㅜㅜ 링크파일을 다운받았긴 한데 어디경로에 있는 releases파일을 지우고 대체해야 될지모르겠습니다.
혹시 LOL->RADS->Solutions->lol_game_client_sln->releases파일을 지우고 넣으면되는건가여? ㅜㅜ
제가 실수 한부분이 북미에서 업데이트를 우선적으로 했을경우에 절대로 "패치하기" 버튼을 누르면 안되는 거였군요.
![2015-06-01 11 08 28](https://cloud.githubusercontent.com/assets/12474829/7914645/41bd938e-08b3-11e5-8b7e-454d1ee92f82.png)
그럼 nginx에 녹색불이 들어오개 하려면 nginx를 실행시켜야하는데 nginx를 실행하려고 터미널에 치니깐 위의 첨부 사진과 같이 나오는데 무슨말인지 모르겠습니다.
제대로 되는게 맞는지 모르겟내여ㅜㅜ
매번 답변해주셔서 고맙습니다.

**Comment by mrz1277** [comment]
터미널을 열고

```
cd /usr/local/var/www
open .
```

하시면 해당 폴더가 파인더로 열리게 됩니다. 거기 보면 releases 폴더가 있는데 기존에 있는걸 지우고 제가 첨부한 링크의 압축파일을 해당 위치에 압축해제 해보세요.

그리고 올려주신 스크린샷은 이미 nginx가 실행되고 있다는 메세지 입니다.

**Comment by ChoiMinJe** [comment]
헉헉 됬습니다!!! 롤이 된다구요!! 고맙습니다 굽신굽신 ㅜㅜ
이제 북미가 먼저 업데이트 되면 "패치하기"를 누르지 않고 시작해야겠내여 고맙습니다!!

**Comment by mrz1277** [comment]
됐다니 다행이네요;; ㅎㅎ 곧 업데이트인데 즐겜하세요~ :)

**Comment by ChoiMinJe** [comment]
![2015-06-01 11 39 02](https://cloud.githubusercontent.com/assets/12474829/7915265/666ff6b4-08b7-11e5-978f-2bf4e8398023.png)
하....챔피언 고르고 로딩화면 넘어가려는데 이렇게 되내여 계속 ㅜㅜ 큭...............
걍 업데이트 기다려야겠습니다.
답변 고맙습니다 정말ㅠㅠㅠㅠ

**Comment by mrz1277** [comment]
흑 ㅠㅠ 혹시 업데이트 다음에도 똑같으면 댓글 남겨주세요 ㅠㅠ

**Comment by j1n-park** [comment]
같은 방식으로 버전차이로 인한 로그인 문제는 해결이 되었는데,
인게임 클라이언트가 실행될때 5.10 버전이라고 튕기는 현상이 있네요.

**Comment by mrz1277** [comment]
@spoon-today 위 방법으로 게임 클라이언트 롤백은 어렵나보군요.. 답변 감사합니다.
