### ISSUE TITLE
케릭터 목소리와 소환사의 협곡에 오신것을 환영합니다 멘트가 안들립니다.

### ISSUE THREAD

**Issue by lhj6784** [mrz1277/LoLKR#18]
패치될때마다 이런 문제가 생기는 것 같은데 이상하게 아무런 말도 안들립니다.

물론 효과음은 나구요 옵션도 확인했습니다.

저번 패치때도그랬는데 이번패치때도 그러네요

패치되고나서 실행하고나면 이렇게 됩니다. 왜그런거죠? 고칠수없나요?

저번패치때는 한참 시간들여서 재설치했었음

**Comment by mrz1277** [comment]
리폿(?) 감사합니다.

방금 확인해보니 언어가 한글로 되어있으면 해당 문제가 발생하는군요.. 저는 영어로 놓고 해서 모르고 있었습니다.(한글 채팅이 하도 답답해서 아예 영어로 하게 된..)

로그를 보니 업데이트 과정에서 한국어 음성 파일의 순서와 경로등이 꼬여서 제대로 읽어들이지 못하는것 같네요.(파일은 존재함) 현재 상태에서 디렉토리만 재배열해서 해결하려 했으나..(잘 안되서 -_-;;) 그나마 빠르고 깔끔한(?) 방법을 찾았습니다. 한국어 인게임 클라이언트만 지우고 재설치 하는건데요, 용량은 약 300메가로 회선 상태에 따라 시간은 조금 소요될 수 있습니다.(제 컴퓨터에선 약 10초정도 소요)

먼저 터미널 여시고 아래 커맨드를 입력해서 기존 게임 클라이언트를 지워줍니다.

```
rm -rf '/Applications/League of Legends.app/Contents/LoL/RADS/projects/lol_game_client_ko_kr/'
```

혹시 권한 거부뜨면 `rm` 앞에 `sudo` 붙이고 관리자 비밀번호 입력하시면 되구요, 롤을 실행시킵니다.

![screen shot 2015-06-03 at 12 22 41 am](https://cloud.githubusercontent.com/assets/2252863/7939607/ad74c038-0986-11e5-92d9-33114bd63370.png)

게임 시작 버튼 누르기 전에 오른쪽 상단을 보면 `온라인(대한민국)` 부분이 있습니다. 클릭하고 언어 선택에서 `Korean` 을 `English` 로 변경해줍니다. 그런 다음 다시 `English`에서 `Korean`으로 변경하면 다운로드가 진행됩니다.

이제 한국어 음성이 잘 나옵니다. :)
