### ISSUE TITLE
요번 패치를하니 아이디와 비밀번호를 제대로 입력해도 로그인오류 가뜨네요

### ISSUE THREAD

**Issue by artists2** [mrz1277/LoLKR#19]
-

**Comment by mrz1277** [comment]
접속하는 서버 지역은 어딘가요?

**Comment by artists2** [comment]
한국서버에요

**Comment by artists2** [comment]
http://kin.naver.com/qna/detail.nhn?d1id=2&dirId=20132&docId=226651881&qb=66GkIOuhnOq3uOyduOyYpOulmA==&enc=utf8&section=kin&rank=1&search_sort=3&spq=0&sp=1&pid=SUayawoRR24ssvRrQhosssssstR-505874&sid=UELUUGKUQpSpzbxfiHVaMg%3D%3D 

이분도 그러신가보네요.. 이런식으로 되요

**Comment by mrz1277** [comment]
아래 경로의 파일 내용을 복사해서 이곳에 붙여주세요

```
/Applications/League of Legends.app/Contents/LoL/RADS/projects/lol_air_client_config_kr/releases/0.0.0.53/deploy/lol.properties
```

터미널 여시고 `cat "/Applications/League of Legends.app/Contents/LoL/RADS/projects/lol_air_client_config_kr/releases/0.0.0.53/deploy/lol.properties"` 하시면 내용이 출력됩니다.

**Comment by artists2** [comment]
어머 패치를 한번더 하니까 되는것 같네요 신경써주셔서 감사합니다 ㅎ
