### ISSUE TITLE
북미서버 전환시 한글패치가 안됩니다

### ISSUE THREAD

**Issue by MCmanty** [mrz1277/LoLKR#2]
한국서버에서는 한국어 영어 두가지설정이 다 있지만 북미서버로 다시 돌아가려하니 한글패치가 안뜹니다!

**Comment by mrz1277** [comment]
북미서버에서 언어가 한글이 안뜬다는 말씀이신가요?
북미는 원래 영어만 지원합니다만..

**Comment by MCmanty** [comment]
답변 감사합니다.
제가 원래는 북미서버에서 한글패치를 해서 썼는데요 이번에 만드신 프로그램으로 패치를 하고 난 후에 지역도 여러가지 선택가능하고
한국서버에서 양아 한글 둘다 선택한데 북미서버에서는 영어만 선택가능하고 한글패치가 안되서 문의 드렸습니다. 혹시 원래 그렇게
의도하신거면 혼란을 드려서 죄송합니다!

2015년 4월 20일 월요일, Jaesung Koonotifications@github.com님이 작성한 메시지:

**Comment by mrz1277** [comment]
북미용 한글패치 따로 스크립트 작성해드립니다. :)

[이곳](https://gist.github.com/mrz1277/65af14c50973f17fe4f0) 다운로드 받으시고 터미널에서

```
chmod +x na_kr.sh
```

로 실행 권한 주시고 실행

```
./na_kr.sh
```

하시면 북미에서도 한글로 이용하실 수 있을겁니다.
즐겜~!

**Comment by MCmanty** [comment]
정말 감사합니다! 이런 그냥 일반 유저인데도 신경써주셔서 정말 감사하고 행복하세요!

2015년 4월 20일 오후 9:27, Jaesung Koo notifications@github.com님이 작성:
