### ISSUE TITLE
LoLKR 응용프로그램을 실행할수 없다는 경고창이 뜹니다.

### ISSUE THREAD

**Issue by sethbefree** [mrz1277/LoLKR#20]
인터넷에서 이런증상에 대해 찾아보기는 했는데 정확한 이유를 모르겠어서 글을 적습니다.
왜그럴까요?
![2015-06-10 2 38 47](https://cloud.githubusercontent.com/assets/12817938/8065086/074b25fa-0f1a-11e5-82c2-c6420f87d3ca.png)

**Comment by mrz1277** [comment]
시스템 환경설정앱을 열고 보안 항목에 들어가면 일반탭 하단에 Mac Appstore 및 확인된 개발자 부분을 선택하고 다시 실행시켜보세요. 메세지가 뜨면 확인 없이 열기 버튼 누르시면 됩니다.

**Comment by sethbefree** [comment]
알려주신대로 했습니다만 여전히 같은 상태 입니다. 혹시나 해서 모든곳 부분을 활성화 시켜서 해봤지만 여전히 같은 메시지만 뜨고 실행이 되지 않습니다.

**Comment by mrz1277** [comment]
운영체제는 요세미티인거죠? 앱을 다시 다운 받고 응용프로그램폴더에 복사한뒤 한번 실행해보세요

**Comment by sethbefree** [comment]
![2015-06-10 3 09 55](https://cloud.githubusercontent.com/assets/12817938/8065753/8a710d1a-0f1e-11e5-89a0-1b917959a9b1.png)
알려주신 방법으로 다시 해봤는데 여전히 안되네요.. 문제가 뭘까요?

**Comment by mrz1277** [comment]
흠 글쎄요.. 혹시 로그인 계정이 관리자 계정이 아닌가요?

**Comment by sethbefree** [comment]
다시 확인해봤는데 관리자 계정이 맞습니다. 이상하네요 문제될게 없는거 같은데 이러네요...

**Comment by mrz1277** [comment]
저도 이런 증상은 처음이라.. 혹시 다른 패키지 앱도 그러는지 먼저 테스트 해봐야겠네요. macnews.tistory.com 같은 블로그에서 패키지 앱(예를들면 http://macnews.tistory.com/m/post/3388) 하나 골라서 똑같이 다운받고 실행해보세요.

**Comment by mrz1277** [comment]
만약 안되면 xcode 로 직접 빌드하는 수 밖에 없겠네요..

**Comment by sethbefree** [comment]
시험해봤는데 마찬가지로 안되네요 제 mac에 문제가 있는듯 하네요 뭐 왜 그럴까요?...
어쨌든 감사합니다

**Comment by sethbefree** [comment]
이유를 찾았습니다 압축을 풀때 기본 아카이브가 아닌 알집으로 했더니 이런 경우가 생겼습니다.
기본 아카이브로 압축을 풀고 실행했더니 정상적으로 작동하네요.
