### ISSUE TITLE
명시되지 않은 오류가 발생한다고 뜹니다.

### ISSUE THREAD

**Issue by ghost** [mrz1277/LoLKR#21]
![screen shot 2015-06-11 at 9 12 13 pm](https://cloud.githubusercontent.com/assets/12469176/8106701/a75ce776-107e-11e5-9990-ef384ea8c3e7.png)
제목과 같이 명시되지 않은 오류가 발생합니다.

![screen shot 2015-06-11 at 9 12 50 pm](https://cloud.githubusercontent.com/assets/12469176/8106710/bf9b6736-107e-11e5-9851-f7955845084d.png)

nginx 프로세스도 정상적으로 돌아가고 있었는데도 오류가 발생하네요.

직접 로그를 확인해보니까 클라이언트랑 서버의 통신이 disconnect 되어있었네요..
어떻게 해결해야할지는 잘 모르겠어서 로그랑 같이 올려봅니다

“`https://drive.google.com/file/d/0B7FW05qngHNIc2YzOGU0SGEzY1k/view?usp=sharing “`

**Comment by ghost** [comment]
제 맥에서 아파치로 웹서버 하나 로컬로 돌리고 있습니다 

포트는 8080이라서 중복되지않을텐데 대체 뭐가문젤까요 ㅠㅠ

//서버 잠시 껐다가 실행해봐도 안되네요..

**Comment by mrz1277** [comment]
사용중인 아파치 서버 포트번호는 어떻게 되나요?

**Comment by ghost** [comment]
8080입니다

**Comment by ghost** [comment]
![a](http://i.imgur.com/DtRuwCl.png)

nginx포트 8010으로 되있는거 확인했습니다

**Comment by mrz1277** [comment]
로그에 에러가 잔뜩 찍혀있긴 하는데 정확히 어디가 문제인지 밝혀내기가 쉽지 않네요. 
이 경우 그냥 롤 클린 설치 후 패치하시는게 더 빠를 수 있겠습니다.^^;

**Comment by ghost** [comment]
현재 북미랑 한국이랑 클라이언트 버전 같나요? 어디서 확인할수있는 곳없나..

**Comment by mrz1277** [comment]
네 같습니다. 서버 버전 확인은 앱 하단에 보면 나와있습니다.

**Comment by ghost** [comment]
재설치하고 오류 해결했습니다!

이슈 닫으셔도 되요 오늘도 감사드려요ㅎㅎ

**Comment by mrz1277** [comment]
네, 즐겜요ㅎㅎ
