### ISSUE TITLE
도와주세요 ㅠㅠ

### ISSUE THREAD

**Issue by Jseul** [mrz1277/LoLKR#23]
brew 설치 자체가 잘 안되는것같아요.
패스워드 입력해서 인스톨 그런 영어 떴었는데,
몇십분 지나도 뭐 상태 변한게 없길래 터미널을 그상태로 껐거든요.

일단  brew 설치 할 때 터미널에 붙여넣으면
Last login: Thu Jun 25 01:00:44 on ttys000
gimjinseul-ui-MacBook-Pro:~ gimjinseul$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
gimjinseul-ui-MacBook-Pro:~ gimjinseul$ 

이런게 뜹니다 ㅠ_ㅠ

물론 다운받은 앱에선 nginx 초록불도 안들어옵니다ㅠㅠ
도와주세용..ㅠㅠ

**Comment by probepark** [comment]
@Jseul 
이미 설치 됬다는거 같은데요?

**Comment by mrz1277** [comment]
@probepark 님 말씀대로 brew 는 이미 설치된것 같구요,
패스워드 입력하라는 곳에서 커서가 깜빡이지 않아도 그냥 패스워드 입력하시면 됩니다.

**Comment by probepark** [comment]
@mrz1277
이슈와 상관없지만 채팅방 같은거 만들면서 잡담이나 나눴으면 하는데 gitter 붙이면 어떠까요?

**Comment by mrz1277** [comment]
@probepark 말씀해주셔서 찾아보고 방금 추가했습니다 :)

**Comment by Jseul** [comment]
![2015-06-26 4 52 52](https://cloud.githubusercontent.com/assets/13036265/8373035/d71ad13e-1c23-11e5-84b0-1834c34dc3a6.png)
brew설치가 된거라면 왜 패치하기 눌러도 저런 안내멘트가 나오는걸까요?ㅠ

**Comment by mrz1277** [comment]
```
rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
```

로 brew 를 지우고 다시 설치해보시는게 어떨까 싶네요.

**Comment by Jseul** [comment]
![2015-06-27 11 03 17](https://cloud.githubusercontent.com/assets/13036265/8392293/bad7790c-1d20-11e5-8a0f-4823f05da723.png)
말씀해주신대로 터미널 입력했더니 이런화면이 뜨네요...;-; 설치됬다면서 못찾는ㄷ...

**Comment by probepark** [comment]
어디신가요? 서울이시면 도움드리고 싶어요

**Comment by Jseul** [comment]
네 서울 거주에요~

네이버 메일앱에서 보냈습니다.----- 원문 메시지 -----
보낸사람: "probe"&lt;notifications@github.com&gt;
받는사람: "mrz1277/LoLKR"&lt;LoLKR@noreply.github.com&gt;
참조: "Jseul"&lt;seul1004_@naver.com&gt;
날짜: 2015. 6. 28 오후 1:42:55
제목: Re: [LoLKR] 도와주세요 ㅠㅠ (#23)

어디신가요? 서울이시면 도움드리고 싶어요

**Comment by probepark** [comment]
@Jseul 가까우시면 직접 찾아뵙겠습니다.ㅋㅋ
