### ISSUE TITLE
지우고 싶은데 대체 어떻게 해야되나요;;;

### ISSUE THREAD

**Issue by guynjoy** [mrz1277/LoLKR#25]
이거 깔고 나서 LOL을 켤때마다
명시되지 않은 오류가 발생했습니다~~   어쩌고 그 메시지가 떠서
LOLKR 다시켜서 또 패치하고 이러는게 너무 번거로워서 그냥 지우고 싶은데
이거 대체 어떻게 지우나요 ㅠㅠ

**Comment by mrz1277** [comment]
명시되지 않은 오류가 뜨는것은 부팅될때 `nginx` 프로세스가 자동으로 실행되지 않아서 생기는 문제입니다.
패치하기 과정에서 자동으로 시작 아이템으로 등록되긴 하는데 간혹 안되는 문제가 발생하기도 하는것 같습니다.

수동으로 등록시키려면 아래 커맨드를 터미널에서 입력해보세요.

```
sudo cp -v /usr/local/opt/nginx/*.plist /Library/LaunchDaemons/
sudo chown root:wheel /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
```

sudo 권한으로 요청하기 때문에 비밀번호를 입력하셔야 합니다.

재부팅을 한 뒤에 똑같이 명시되지 않은 오류가 계속 발생하다면 부팅할때마다 터미널 창에서 수동으로

```
nginx
```

를 입력해 주셔야 합니다. (매번 패치하기 버튼을 누르실 필요는 없습니다.)

그래도 이 과정이 귀찮으시다면 자동 업데이트 방지 스위치를 해제(끔)에 두면 굳이 LoLKR을 지우지 않더라도 해당 문제는 발생하지 않으실 겁니다.

**Comment by guynjoy** [comment]
nginx 를 터미널에 쓰면 LOLKR이 재실행 된다고 설명에 써있어서 아는데 그거 안되요
그냥 패치를 해야지 그 명시되지 않은 오류가 안떠요..

저 수동등록 하는데 필요한 비밀번호가 뭔가요?

**Comment by mrz1277** [comment]
brew 설치하셨을때처럼 관리자(맥 로그인) 비밀번호입니다.

**Comment by mrz1277** [comment]
근데 nginx 를 터미널에 입력했을때는 어떤 메세지가 뜨나요?

**Comment by guynjoy** [comment]
Last login: Thu Jul  2 09:39:43 on ttys000
Leeui-MacBook-Pro:~ Joseph$ nginx
Leeui-MacBook-Pro:~ Joseph$ 

그냥 이렇게 되네여

**Comment by mrz1277** [comment]
원래 아무것도 안뜨는게 정상이에요. 저 상태에서 명시되지 않은 오류가 뜨나요?

**Comment by guynjoy** [comment]
네 알려주신데로 업데이트 허용으로 해놨는데도 명시되지 않는 오류가 뜨네요...
그냥 지우는법좀 알려주세요

**Comment by mrz1277** [comment]
아무래도 nginx 관련 에러는 아닌것 같습니다. 자세한 내용은 로그를 봐야할것 같구요..

완전히 지우시려면 시간이 좀 소요되지만, 롤 클린설치를 권장합니다.
그러면 LoLKR 앱의 설치 유무와 관계없이 사용하실 수 있습니다.

기존 League of Legends 앱을 지우시고 공식 홈페이지에서 다시 다운받아 설치하시고 [기존의 한국서버 우회 접속 방법](http://macnews.tistory.com/2057)들로 이용해보세요.
