### ISSUE TITLE
이런 경우에 패치하기 버튼을 누르지 말라는 말씀이신가요??

### ISSUE THREAD

**Issue by Jseul** [mrz1277/LoLKR#26]
<img width="368" alt="2015-07-09 9 36 56" src="https://cloud.githubusercontent.com/assets/13036265/8595148/c321e938-2682-11e5-9b72-f1118cda9f7c.png">
<img width="1271" alt="2015-07-09 9 37 22" src="https://cloud.githubusercontent.com/assets/13036265/8595149/c32c20b0-2682-11e5-9e44-97caf913038f.png">

북미는 5.13이고
한국이 5.12인데

롤 클라이언트 켜서 게임시작 버튼 뜰 때까지 패치 하는거 내비뒀거든요 ㅠ
지금 물론 접속이 안되구용

이럴때에 패치하기 버튼 누르면 안된다는건가요?
brew부터 다시 설치중이에요 처음부터!! ㅠ

**Comment by Jseul** [comment]
<img width="503" alt="2015-07-09 9 57 37" src="https://cloud.githubusercontent.com/assets/13036265/8595731/9228f0f8-2685-11e5-917c-6ab4ddf2a08e.png">
<img width="376" alt="2015-07-09 9 57 45" src="https://cloud.githubusercontent.com/assets/13036265/8595730/92247e6a-2685-11e5-8c9e-ce776cda6c78.png">

일단 한번 패치하기 눌러봤는데 이러네요...ㅠ 실행할수 없는건가염..

**Comment by star114** [comment]
프로그램의 동작에 대해 잘못 이해하고 계신 것 같습니다.
nginx 는 롤 패치가 이루어지기 전에 설치 및 동작 중이어야 하며,
nginx 가 업데이트 서버를 우회하여 실행할 수 있도록 동작하고 있는 것 같습니다.
따라서 이미 업데이트가 완료된 상황에서는 한국서버에서 동일 버전으로 업데이트 되기를 기다릴 수 밖에 없을 것으로 보입니다.

북미서버가 5.14 한국서버가 5.13 상황이 되면 이제 잘 될듯 하네요.

**Comment by mrz1277** [comment]
@star114 님께서 잘 설명해 주셨는데 다시 한번 @Jseul 님을 위해 정리해드릴게요.

아시다시피 한국서버가 5.13으로 업데이트 되기 전까지는 접속이 안되시구요,
업데이트가 될때까지 향후 몇 일간 스위치를 **허용**으로 두시면 해당일에 업데이트가 정상적으로 진행됩니다.

그리고 한국 5.13으로 업데이트가 정상적으로 된 시점부터는 다시 스위치를 **방지**로 두시고 다음 한국 서버 업데이트 5.14가 나오기 전까지 유지하시면 됩니다.

이전 버전부터 문제를 겪으신것 같은데 개인적으로 안타깝네요;;
