### ISSUE TITLE
어떡해야 하죠?

### ISSUE THREAD

**Issue by califoniaroll** [mrz1277/LoLKR#27]
화면에 이런 게 떴어요
북미 서버를 먼저 선택하고 업데이트가 완료되어야 합니다
어떡해야 하죠?
제가 컴맹이라서요 ㅠㅠ

**Comment by mrz1277** [comment]
그림이 안보이네요 다시 올려주세요;;

**Comment by califoniaroll** [comment]
네

**Comment by califoniaroll** [comment]
<img width="1280" alt="2015-07-10 9 08 41" src="https://cloud.githubusercontent.com/assets/13255715/8618315/f2a8f1f4-2747-11e5-97bc-9e22b0962e22.png">

**Comment by mrz1277** [comment]
맥에 롤을 클린 설치하셨군요.

메세지 내용은 한글패치를 하려면 먼저 북미용으로 게임 클라이언트가 설치(업데이트)가 다 완료된 상태에서 진행되어야 한다는 것입니다.

문서를 보면 아시겠지만 일단 지금 서버 업데이트 기간(북미 5.13, 한국 5.12)이기 때문에 북미용을 설치하고 한글패치를 하셔도 북미 버전으로 깔려서 한국서버가 5.13으로 업데이트 되기전 까지는 접속하실수 없습니다.

일단 한국서버가 정상적으로 5.13으로 업데이트 되고나면, 그때 다시 패치하기를 한번해주시고 현재처럼 업데이트 스위치를 방지쪽으로 켜두고 계시면 다음 업데이트 기간(5.14)때 부터는 정상적으로 이용하실 수 있습니다. ^^;

**Comment by califoniaroll** [comment]
아 그렇군요 정말 감사합니다 ㅠㅠ 전 이제 앞으론 맥북으로 롤 못 돌리는 줄 알고 ㅠㅠ
정말 감사합니다

**Comment by mrz1277** [comment]
패치와 관련해서 궁금한점 있으시면 이곳에 언제든 올려주세요^^

**Comment by califoniaroll** [comment]
그럼 지금 북미 롤 버전이 5.13인데 한국 롤이 5.13으로 업뎃되면 바로 롤kr로 패치를 하면 되는 건가요, 아니면 북미 롤 5.14패치를 받은 다음에 롤kr 패치를 해야 하는 건가요?

**Comment by mrz1277** [comment]
한국 서버가 5.13 이 되면 바로 패치해주시면 됩니다.

**Comment by califoniaroll** [comment]
아 그렇군요 감사합니다
-----Original Message-----
