### ISSUE TITLE
오류 좀봐주시겟어요?

### ISSUE THREAD

**Issue by bboysaw** [mrz1277/LoLKR#28]
잘은몰라도 설명대로 모두한것같은데..모가문제일까요?
처음부터 다 다시 설치해봐야할까요?

![2015-07-12 9 21 57](https://cloud.githubusercontent.com/assets/13299469/8637799/cc030a06-28de-11e5-9e45-357b78f95102.png)

**Comment by mrz1277** [comment]
북미롤은 제대로 설치된것 같은데 다른 패치프로그램 사용등으로 경로가 확인이 안되는것 같네요.

터미널에 아래 커맨드를 복사해서 입력하고

```
cd "/Applications/League of Legends.app/Contents/LoL/RADS/projects/lol_air_client_config_na/releases"
```

경로가 제대로 바뀌는지 한번 확인해보세요. 
만약 경로가 제대로 안바뀐다면 현재 설치된 롤을 지우고 처음부터 다시 클린하게 설치해보시기 바랍니다.

그리고 지금 패치기간이기 때문에 `한글패치`가 끝나도 한국서버에 접속할 수는 없습니다. 자세한 내용은 아래 링크 참고하세요.
https://github.com/mrz1277/LoLKR/issues/27
