### ISSUE TITLE
그래도 안돼요 ㅠㅠ

### ISSUE THREAD

**Issue by califoniaroll** [mrz1277/LoLKR#29]
<img width="1280" alt="2015-07-14 9 28 01" src="https://cloud.githubusercontent.com/assets/13255715/8673221/b7bf3b22-2a6f-11e5-9923-24f1d22b34e6.png">
한국서버가 5.13로 패치돼서 롤kr 돌렸거든요.
그래서 스위치 빼고 한글패치 했는데 에러가 떠요.
ㅠㅠ
어떡해야 하죠?

**Comment by mrz1277** [comment]
UI 오류라 수동으로 스크립트를 실행시켜주시면 될 것 같네요.
LoLKR 앱을 오른쪽 버튼 누르면 패키지 내용보기 메뉴가 있습니다.
그리고 Contents/Resources 폴더로 들어가면 1_nginx.sh 2_download_version.sh 3_lol.sh 파일이 있습니다.
번호대로 차례로 터미널 창에 드래그 하고 실행해보세요.

혹시 이전과 똑같은 메세지가 뜨고 패치 완료가 안된다면 롤을 다시 클린설치 하시는 방법도 추천합니다.

**Comment by califoniaroll** [comment]
원격지원 좀 해주실 수 있으시나요?
-----Original Message-----
