### ISSUE TITLE
귀찮게 해서 정말 죄송합니다 ㅠㅠ

### ISSUE THREAD

**Issue by califoniaroll** [mrz1277/LoLKR#30]
<img width="1280" alt="2015-07-18 2 01 44" src="https://cloud.githubusercontent.com/assets/13255715/8760417/9318705c-2d55-11e5-8c7a-f7c43db3865e.png">
이제 업데이트 스위치를를 허용에 두고 롤을 실행하면 되는 건가요?

**Comment by mrz1277** [comment]
네 맞습니다
