### ISSUE TITLE
이게 맞는 건가요?

### ISSUE THREAD

**Issue by califoniaroll** [mrz1277/LoLKR#31]
<img width="1280" alt="2015-07-18 2 40 02" src="https://cloud.githubusercontent.com/assets/13255715/8760491/0dfcd1dc-2d5b-11e5-8eb9-c745778c0b44.png">
롤 kr 패치가 완료되서 스위치를 허용으로 내리고 롤을 실행시켰는데 위와 같은 화면이 떴어요.
이게 맞는 건가요?

**Comment by mrz1277** [comment]
네 북미섭 업데이트가 되고 잇는데 완료되면 오른쪽 상단에 국가를 한국으로 변경하시면 됩니다

**Comment by califoniaroll** [comment]
감사합니다!

**Comment by califoniaroll** [comment]
어..... 그런데 국가에 한국이 없는데요?

**Comment by mrz1277** [comment]
South Korea 없나요?

**Comment by mrz1277** [comment]
또는 그냥 Korea 라고 있을텐데.. 없으면 패치하기를 다시 하셔야 합니다

**Comment by califoniaroll** [comment]
롤 kr 패치하기요?
-----Original Message-----

**Comment by califoniaroll** [comment]
없네요 ㅠㅠ

**Comment by califoniaroll** [comment]
그럼 패치를 다시 해야 하는 건가요?

**Comment by mrz1277** [comment]
네 lolkr 패치하기를 다시 해보시길 바랍니다

**Comment by califoniaroll** [comment]
그래도 안돼서 지금 롤을 다시 깔고 있는 중입니다.
-----Original Message-----

**Comment by califoniaroll** [comment]
그럼 일단 북미롤을 깔고. kr 패치하고. 스위치를 허용으로 내리고. 롤 실행시켜 주면 되는 거죠?
-----Original Message-----

**Comment by mrz1277** [comment]
네 북미롤 업데이트끝나고 lolkr 패치하면 한국섭은 접속할수있고 패치는 방지로 켜두셔야 합니다

**Comment by califoniaroll** [comment]
그래도 안돼요.
-----Original Message-----

**Comment by mrz1277** [comment]
음 제가 원격으로 한번 봐드릴까요?

**Comment by califoniaroll** [comment]
그러실 수 있으시나요? 된다면 정말 감사드립니다!
-----Original Message-----

**Comment by mrz1277** [comment]
[크롬 원격 프로그램](https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp?hl=ko) 먼저 설치해주시고 접속 코드 알려주시면 됩니다.

**Comment by califoniaroll** [comment]
다운로드 버튼이 안 보이네요 ㅠㅠ
보이긴 보이는데 그건 윈도우용이고요 ㅠㅠ
-----Original Message-----

**Comment by mrz1277** [comment]
아.. 브라우저를 먼저 [크롬](https://www.google.com/chrome/browser/desktop/index.html)으로 설치하셔야 합니다. 사파리는 지원안해서..

**Comment by califoniaroll** [comment]
3078-9686-6395
-----Original Message-----

**Comment by califoniaroll** [comment]
보냈습니다~
-----Original Message-----

**Comment by califoniaroll** [comment]
코드가 만료되서 다시 보낼게요.
6949-4777-2263
-----Original Message-----

**Comment by califoniaroll** [comment]
그냥 내일 해주세요. 제가 일이 좀 있어서요.
아무튼 정말 진심으로 감ㅅ드립니다.
몇심만 유저의 일부인 저를 위해서 선뜻 원격 지원까지 해주시겠다고 나서시고.....
정말 진심으로 감사드립니다.
-----Original Message-----

**Comment by mrz1277** [comment]
아... 네, 여기에 댓글 남겨주시면 바로 확인해드릴게요

**Comment by califoniaroll** [comment]
원격지원 해주실 수 있으시나요?

**Comment by mrz1277** [comment]
지금 가능합니다

**Comment by califoniaroll** [comment]
원격지원 가능할 때 연락주세요~
-----Original Message-----
