### ISSUE TITLE
안녕하세요! 패치 감사히 쓰고있습니다. 한가지 질문드릴께있어요ㅠ

### ISSUE THREAD

**Issue by etro6775** [mrz1277/LoLKR#32]
패치 성공후 정상적으로 게임 이용이 가능한데

대기실에서 한글채팅은 가능한데 게임 시작후 게임내에서 채팅이 안됩니다ㅠ

예를 들어 "감사합니다" 를 게임 내 채팅에서 쓰면 "ㄱ ㅏ ㅁ ㅅ ㅏ ㅎ ㅏ ㅂ ㄴ ㅣ ㄷ ㅏ" 이런식으로 뜨네요...

어떻게 해결해야하나요?

**Comment by mrz1277** [comment]
이건 맥 게임 클라이언트 한글 오류라서 (아직까니) 고칠 수 있는 방법이 없습니다...
