### ISSUE TITLE
nginx 가 자꾸 사라져요

### ISSUE THREAD

**Issue by catveloper** [mrz1277/LoLKR#33]
nginx 가 자꾸사라지네요 그래서 lol에서 계속 오류가 나고요 ㅠㅠ 

매번 킬때마다 다시 깔고 설치하는데 오래걸리지는 않지만 번거로운데 정상은아닌거죠?

**Comment by mrz1277** [comment]
텍스트 편집기로 `/usr/local/etc/nginx/nginx.conf` 파일을 여시고

```
proxy_pass  http://l3cdn.riotgames.com;
```

아래 부분에 다음 두 줄을 추가해주세요. 
찾아보시면 총 두 부분이 있습니다.

```
proxy_connect_timeout 60s;
proxy_read_timeout 60s;
```

이렇게 해도 오류가 계속 나면 다시 알려주세요.

**Comment by catveloper** [comment]
시키신대로 작업했습니다 두줄은 총두부분에 동일하게 두줄 추가했는데요 여전히 nginx 는 재시동하고나서 비활성화되있구 롤은 접속하면 명시되지않은 오류라고 뜹니다.. 스샷 첨부를보시면 이렇게 되있습니다

**Comment by catveloper** [comment]
<img width="1440" alt="2015-07-21 7 00 40" src="https://cloud.githubusercontent.com/assets/13418076/8788638/c3c1a066-2f76-11e5-99e4-6175ade625a5.png">
<img width="1440" alt="2015-07-21 7 00 48" src="https://cloud.githubusercontent.com/assets/13418076/8788645/cbd8303a-2f76-11e5-89dd-106904a12543.png">
<img width="1440" alt="2015-07-21 7 02 08" src="https://cloud.githubusercontent.com/assets/13418076/8788648/d0c366be-2f76-11e5-8f5b-63c377fc24b2.png">
