### ISSUE TITLE
시키신대로 했는데 잘안되네요 ㅠㅠ

### ISSUE THREAD

**Issue by catveloper** [mrz1277/LoLKR#34]
<img width="1440" alt="2015-07-21 7 00 40" src="https://cloud.githubusercontent.com/assets/13418076/8789603/24b9204e-2f7f-11e5-8caa-41a3cd7c1b47.png">
<img width="1440" alt="2015-07-21 7 00 48" src="https://cloud.githubusercontent.com/assets/13418076/8789604/24b9ceea-2f7f-11e5-83a9-266d69cde9e1.png">
<img width="1440" alt="2015-07-21 7 02 08" src="https://cloud.githubusercontent.com/assets/13418076/8789602/243ae328-2f7f-11e5-96ae-828de600e83d.png">

**Comment by catveloper** [comment]
오히려 이거 하고나서 롤kr이 자꾸 오류나네요 ㅠ

**Comment by mrz1277** [comment]
로그를 한 번 봐야겠네요. `/usr/local/var/log/nginx/error.log` 파일과 `/Applications/League of Legends.app/Contents/LoL/Logs` 폴더를 압축해서 이곳에 올려주세요.
