### ISSUE TITLE
패치후에 재접속이 안됩니다.

### ISSUE THREAD

**Issue by imkimchi** [mrz1277/LoLKR#35]
실수로 LoLKR에서 허용으로 되어있어서 클라이언트가 업데이트 되길래 바로 클라이언트를 종료하고나서
업데이트 방지로 돌렸는데 업데이트가 다시 진행되어서 한국 서버로 접속이 잘되었는데 
게임 시작후에 게임 로딩창에 들어가면 
"연결이 끊겼습니다. 인터넷 연결 상태를 확인한 후 다시 시도해 주세요."라고 나오면서 재접속이 계속 불가능합니다
재부팅도 해보고 롤클라이언트도 완전히 종료후에 재접속해봤는데도 계속 안되네요..

뭐가 문제일까요

**Comment by mrz1277** [comment]
지금도 여전히 문제가 발생하나요?

**Comment by imkimchi** [comment]
네 여전히 발생합니다.

**Comment by mrz1277** [comment]
저도 겪어본적이 없는 현상이라 잘 모르겠네요. 
업데이트가 부분적으로 되면서 생긴 문제가 아닐까 추측해봅니다.

지금 한국서버도 5.14로 업데이트 됐으니 불편하시겠지만 롤 클린설치를 하시는편이 좋을것 같습니다..^^;

**Comment by imkimchi** [comment]
오 이제야 업데이트되었군요
이슈 닫아주셔도 됩니다 항상 감사합니다~
