### ISSUE TITLE
NA서버 인게임에서 모든 사운드가 안들리는 버그있습니다.

### ISSUE THREAD

**Issue by imkimchi** [mrz1277/LoLKR#36]
다른서버들도 그런진 모르겠지만 인게임에서 모든 소리가 아예 안들립니다 해결부탁드려요!

**Comment by mrz1277** [comment]
이렇게 한번 해보세요.
업데이트 스위치를 방지에 둔 상태에서, 롤을 끄고 터미널에 아래 커맨드를 입력해서 기존 영어 게임 클라이언트를 지웁니다.

```
rm -rf "/Applications/League of Legends.app/Contents/LoL/RADS/projects/lol_game_client_en_us"
```

그리고 다시 롤을 켜서 우측 상단의 서버 선택에서 한국서버 한글로 세팅을 한 다음 다시 북미 영어로 세팅하면 새로 클라를 내려받을겁니다.

아마 다음 한국서버 패치때도 똑같은 증상이 반복될 수 있으니, 북미섭을 주로 사용하신다면 본 패치를 아예 안쓰시는게 좋구요, 두 서버를 번갈아 쓰신다면 롤앱 자체를 두 개 깔고 이름만 바꿔서 한 군데에만 한글패치를 적용하는 방법도 있겠네요.(피시방에서 쓰는방법)

**Comment by mrz1277** [comment]
일주일이 지나도 추가 글이 없으므로 이슈를 닫겠습니다. 문제가 있으면 다시 열어주세요.
