### ISSUE TITLE
새롭게 북미서버 다운받아서 lolkr 사용하기

### ISSUE THREAD

**Issue by kwondongdong** [mrz1277/LoLKR#37]
기존에 있던 롤이 업데이트가 되어서 새롭게 북미클라이언트를 다운받아서 패치 방지하는 방법은 뭔가요?

**Comment by mrz1277** [comment]
[본문 중간](https://github.com/mrz1277/LoLKR#시작-전-주의사항)에 보시면 알겠지만 북미 업데이트 기간에는 lolkr로 패치하셔도 한국서버에 접속할 수 없습니다.
