### ISSUE TITLE
어떻게 해야할지 모르겠어요ㅠㅠ

### ISSUE THREAD

**Issue by jaymoon0304** [mrz1277/LoLKR#38]
몇가지 질문이 있어요.
1. 오세아니아서버를 한국서버로 변경해서 사용하고 있었는데, 북미로 변경 후 패치를 해야하나요?
2. brew 설치 진행하려고 명령어를 터미널에 입력했는데

==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1
==> The following directories will be made group writable:
/usr/local/.
/usr/local/include
/usr/local/lib/pkgconfig
==> The following directories will have their group set to admin:
/usr/local/.
/usr/local/include
/usr/local/lib/pkgconfig

Press RETURN to continue or any other key to abort

이렇게 뜨더니 nginx말고 다른 프로그램 설치하라고 뜨더라구요.
일단 그거 설치는 했는데, 그후 명령어를 입력해도 더 뭘 설치하라고 뜨진 않았어요.
그리고는 nginx에 불이 안 들어와요..
롤은 명시되지 않은 오류가 있다며 아예 클라이언트 켜지지도 않아요.
이거 어떻게 해야하나요?

**Comment by mrz1277** [comment]
저 위의 메세지에서 엔터키를 누르시면 설치가 계속 진행될겁니다.
nginx가 설치되지 않으면 해당 에러가 뜹니다.

그리고 업데이트 기간에는 본 프로그램으로 패치한다고 해도 한국섭에 접속할 수 없습니다. [참고](https://github.com/mrz1277/LoLKR#시작-전-주의사항)
