### ISSUE TITLE
'대한민국' 서버가 안뜨고 '북미'로 뜨네요

### ISSUE THREAD

**Issue by hyeonseolee** [mrz1277/LoLKR#39]
지금 북미는 5.16, 한국은 5.15인데 오늘 처음으로 LoLKR깔아서 패치를 하고 프로퍼티까지 고쳐서 한국서버로 변환시키긴 했는데 대한민국이 안뜨고 북미로 나오는데 고치는방법 없나요? 로그인이 안되는건 당연한거고..최소 그거라도 바뀌면 맘이 좀 편할텐데 혹시 제가 뭘 잘못했나요?

**Comment by mrz1277** [comment]
lolkr 패치하면 다른 프로퍼티는 수정할 필요가 없습니다. 기존에 다른 우회 방법을 사용하셨다면 충돌이 생길 수 있으니 기존 롤을 지우고 클린설치한 다음 다시 lolkr패치를 해보세요.
