### ISSUE TITLE
서버접속이 안됩니다.

### ISSUE THREAD

**Issue by jungwoot** [mrz1277/LoLKR#4]
저도 아래분과 같은 문제로 접속이 안됩니다. 계속 명시되지 않은 오류가 발생했다고 뜨네요.  nginx 도 초록불로 잘 뜨는데 말입니다. 뭐가 문제인지 잘 모르겠어요 ㅠㅠ
https://drive.google.com/open?id=0B0DYo6CCXwnYfmQ3LW1SVWc2UWhTVHpNc3dEUmdHYkFkRWtZaGxBZmdPX2lzYnVtY1kwUlk&authuser=0

로그가 이게 맞는지 잘 모르겠네요.

**Comment by mrz1277** [comment]
파일 조회에 권한이 필요하네요

**Comment by jungwoot** [comment]
혹시 그건 어떻게 해결할수 있는지 여쭤볼수 있을까요..?

**Comment by mrz1277** [comment]
위에 첨부해주신 구글 드라이브 열람에 권한이 필요합니다.
여기 댓글로 첨부해 올려주세요

**Comment by jungwoot** [comment]
아 공유 했습니다! 죄송합니다 제가 잘 몰라서요..

**Comment by mrz1277** [comment]
흠 해당 로그만 봐서는 정확히 모르겠네요..
아래 명령어를 터미널에서 실행하면 로그파일이 전부압축 되는데 그걸 보내주시면 다시 한번 확인해볼게요

```
find "/Applications/League of Legends.app/Contents/LoL/RADS/" -name '*.log' -print | zip logs -@
```

**Comment by mrz1277** [comment]
아, 그리고 혹시 하드에 용량이 충분하시다면 문제 확인하는동안 롤을 하나 더 설치해서 테스트 해보시겠어요?
[https://signup.leagueoflegends.com/en/signup/redownload](https://signup.leagueoflegends.com/en/signup/redownload)에서 다운로드 받으시고 Applications 폴더에 복사하기 전에 파일이름을 League of Legends2 같이 바꿔서 복사한 뒤 실행해서 북미섭 업데이트까지 완료해보세요. 그런다음 한글 패치할때 롤 경로 설정에서 바꾼 이름을 선택하고 패치 한번 해보세요.

**Comment by jungwoot** [comment]
아 재설치를 하니까 잘되네요!
신경쓰시게 해서 죄송합니다! ㅠㅠ
