### ISSUE TITLE
client version is reject by server 5.16.15_08_18_12_40 ;'(

### ISSUE THREAD

**Issue by chenglu** [mrz1277/LoLKR#41]
![2015-08-24 7 39 01](https://cloud.githubusercontent.com/assets/2258420/9430773/3832a59a-4a33-11e5-92ba-7eff850a8de8.png)

**Comment by chenglu** [comment]
when last time auto upgrade my client to this version then it didn't work.

**Comment by mrz1277** [comment]
You can't apply this patch(LoLKR) when version is differ between NA and KR. It means you should do that work before or after upgrade period(5.15->5.16). And you can't login before KR server is updated. Maybe until 25 August 13:00 KST. Patch this program again after that.
