### ISSUE TITLE
하.. 처음에 됐는데 롤 실행하면 명시되지 않은 오류 뜨고, nginx에 초록불이 안들어와서 nginx -s reload 터미널에 치니까 nginx: [error] open() "/usr/local/var/run/nginx.pid" failed (2: No such file or directory)라고 오류라네요

### ISSUE THREAD

**Issue by hanjoohwan** [mrz1277/LoLKR#42]
하.. 처음에 됐는데 롤 실행하면 명시되지 않은 오류 뜨고, nginx에 초록불이 안들어와서 nginx -s reload 터미널에 치니까 nginx: [error] open() "/usr/local/var/run/nginx.pid" failed (2: No such file or directory)라고 오류라네요

**Comment by mrz1277** [comment]
그냥 nginx 라고 쳐보세요

**Comment by hanjoohwan** [comment]
<img width="569" alt="2015-08-28 7 53 03" src="https://cloud.githubusercontent.com/assets/14014495/9544795/6ce7a7ac-4dbe-11e5-8b0f-75f7e263b82e.png">
이렇게 되는게 맞는건가요?

**Comment by mrz1277** [comment]
그럼 brew uninstall nginx 로 지웠다가 brew install nginx 로 설치하고 다시 패치해보세요

**Comment by hanjoohwan** [comment]
됐어요! 감사합니다ㅋㅋ

**Comment by mrz1277** [comment]
재부팅하고도 잘 실행되는지 마지막으로 확인해보세요

**Comment by hanjoohwan** [comment]
네 게임 실행도 잘 되네요 감사합니다

**Comment by mrz1277** [comment]
네 즐롤!
