### ISSUE TITLE
명시되지 않은 오류가 발생하였습니다. 자세한 사항을 로그를 확인해 주시기 바랍니다.

### ISSUE THREAD

**Issue by yoon0803** [mrz1277/LoLKR#43]
잘되다가 이렇게 뜨면 북미섭이 패치 중인가요?

nginx 에 불이 안들어오고 안되는데요

이럴땐 뭐가 문제인가요?

아마 북미썹이 패치하고 난 후에도 이렇게 되는거 같은데... 지금은 여기 뜨는 바로는 북미썹 5.16 한국썹 5.16

같은 걸로 뜨는데 안되네요

**Comment by mrz1277** [comment]
https://github.com/mrz1277/LoLKR/issues/42 여기 참고해주세요
