### ISSUE TITLE
lolstar 는 어떻게 사용하나요?

### ISSUE THREAD

**Issue by yoon0803** [mrz1277/LoLKR#44]
방에 들어가면 자동으로 받아주는 건줄 알았는데 안되고 게임시작 후에도 안받아지는데...

들어가면 game was end 라고 뜹니다.

사용 방법 좀 알려주세요

**Comment by mrz1277** [comment]
http://mrz1277.github.io/LoLStats/ 참고요

**Comment by yoon0803** [comment]
게임이 들어가도 자동으로 안떠요
