### ISSUE TITLE
좋은 어플 감사합니다 하지만..

### ISSUE THREAD

**Issue by Hanchhoa** [mrz1277/LoLKR#46]
제맥이 지원이 안되는건지, 제가 못하고있는건지는 모르겟지만 오늘 북미서버가 5.17로 업데이트되어서 요근레에는 못하겟지만 제가 스카이프로 화면공유하면서 도와주실수있는지... nginx가 설치도안되고ㅠㅠ 말안하셔도되요..~ 되시면 kwonhyeok123 으로 친구추가해주시면 감사하겟습니다 ㅎㅎ~

**Comment by mrz1277** [comment]
@Hanchhoa 스카이프 확인해 보세요.
