### ISSUE TITLE
lolkr 제대로 설치하고 업데이트 방지에 놓고 게임 들어갔는데 업데이트 진행됐어요ㅜㅜ

### ISSUE THREAD

**Issue by hanjoohwan** [mrz1277/LoLKR#47]
뭐가 문젠지 모르겠어요ㅜㅜ
그리고 혹시 업데이트 됐을 때, 되돌릴 수 있는 방법 있나요?

**Comment by mrz1277** [comment]
안타깝지만 업데이트 되셨다면 방법이 없습니다.. 그래도 다행인건 이번 업데이트는 내일 새벽에 진행된다고 합니다. 

업데이트 후에 패치하기를 다시 한번 해주시고 스위치를 한번씩 껏다 켜서 방지에 다시 두고 다음엔 제대로 동작하길 바랄게요.
