### ISSUE TITLE
압축 해제 후 실행을 못 하겠어요.

### ISSUE THREAD

**Issue by arche1011** [mrz1277/LoLKR#48]
다운로드를 받고 압축을 풀면 실행화일이 전부 다 풀려서 첨부 파일처럼 표시됩니다.

어떻게 해야 하나요. 

혹시 해결방법 아시면 알려주시면 감사하겠습니다.

![2015-09-09 9 16 07](https://cloud.githubusercontent.com/assets/14198281/9761452/cad7f45c-5737-11e5-8386-c8e30ba07ca9.png)

**Comment by mrz1277** [comment]
https://github.com/mrz1277/LoLKR/releases/download/latest/LoLKR.zip 이걸 다운받으세요

**Comment by arche1011** [comment]
감사합니다.^^
