### ISSUE TITLE
5.18버전 업데이트 후에 북미섭은 접속이 되는데 한국섭은 접속이 되지 않습니다.

### ISSUE THREAD

**Issue by LeeDongKwon** [mrz1277/LoLKR#49]
5.18버전 업데이트 후에 클라이언트 좌측 상단의 버전명이 아직도 5.17_8_31 로 나오길래

그냥 패치가 아직 안되는 것인가? 했는데 북미섭은 정상적으로 접속이 되고

한국서버는 아직 정상적으로 접속이 되지 않네요. 패치앱 자물쇠표시 양쪽엔 분명 한국/북미섭 모두

5.18버전이라고 나와있는데 왜 이런 현상이 나타나는 것일까요?

ngnix 새로 패치하기도 해보고 롤 재설치도 해봤습니다만 같은 문제가 발생하네요!

**Comment by mrz1277** [comment]
리폿 감사합니다. 저도 방금 해보니 업데이트가 진행이 되지 않는군요. 문제 원인 발견하는대로 업뎃하도록 하겠습니다.

**Comment by ysw8572** [comment]
저같은 경우엔 북미서버도 5.17로 되어있고 한국서버도 5.17로 되어있네요ㅠ 
빠른 확인 부탁 드리겠습니다!

**Comment by ChoiMinJe** [comment]
LOL KR로 삭제해보고 2번이나 재설치 했는데도 북미에서는 5.18뜨는데
한국 업데이트 받고나서 들어가면 한국 5.17떠있고 북미도 5.17 되어 있어버리네여 ㅜㅜ
흑흑 ㅜㅜ

**Comment by mrz1277** [comment]
혹시 5.18 업데이트 후에 lolkr 패치 허용 안하고 이전 버전(5.17)으로 접속 되신분 계신가요?

**Comment by ysw8572** [comment]
접속은 했지만 5.17 클라이언트 거부라고 뜨면서 로그인이 안되더군요

**Comment by mrz1277** [comment]
@ysw8572 그럼 lolkr 패치 허용 전후로 모두 똑같이 거부라는 메세지가 뜬건가요?

**Comment by ysw8572** [comment]
네 전후 똑같았습니다ㅜ

**Comment by voou1312** [comment]
저같은경우에 올려주신 롤 한국서버 패치 프로그램 상에서 한국 5.18 북미 5.18 이라고 써있으나
롤 로그인창에선 클라이언트가 맞지 않다고 접속이 안됩니다.

**Comment by mrz1277** [comment]
참고로 LoLKR 하단의 버전은 롤 업데이트 서버 버전입니다. 클라이언트 버전이 5.17 인데 북미는 접속되고 한국은 접속이 안되서 난감합니다. 혹시 여기 윈도에서 롤 설치되신분들중에 클라이언트 버전(로그인 화면 죄상단) 알려주실 분 있나요? 지금 버추얼박스에서 롤 설치중인데 너무 오래걸리네요.

**Comment by jooneyp** [comment]
저 또한 같은 문제가 생기네요.lolKR덕에 VM에서 롤 지운지 오래되어 확인이 불가능합니다.. ^^;

**Comment by msuksong** [comment]
특이한 경우인데, 한국이 북미보다 먼저 5.18패치가 적용되어 그런 것 같습니다.

**Comment by jooneyp** [comment]
한국이 먼저 패치되었다면 업데이트 허용 시 한국서버에서 업데이트를 받아와야할텐데..
지금 구조는 단순히 북미섭에서 들어오는 업데이트를 블락할지 안할지만 결정해주는 거였군요.
클라이언트 자체를 한국 업데이트 서버로 연결하는것은 힘든 작업일까요? 잘 몰라서리..

**Comment by mrz1277** [comment]
@jooneyp 아쉽게도 한국 업데이트 서버엔 윈도용 파일만 서브하고 있더라구요;;

**Comment by mrz1277** [comment]
북미 롤 홈페이지에 가보니 @msuksong 님 말씀대로 아직 북미가 5.18 패치가 안되어있군요.(한국이 먼저 진행되는 경우는 저도 처음입니다.) 한국시간으로 오늘 오후 7시에 진행될 예정이랍니다. 한국 유저분들은 몇 시간만 참으셔야 겠습니다;; 참고url http://status.leagueoflegends.com/?en_US#na @msuksong , @jooneyp 님 감사합니다.

**Comment by g10204** [comment]
아직 안되는군요 ㅠㅠ
제가 알기로 오세아니아 서버가 북미보다 우리나라 서버랑 잘 맞는걸로 알고있는데요
프로그램을 북미 말고 오세아니아 서버에서 가지고 오게 수정하는게 어떨까요??

**Comment by ChoiMinJe** [comment]
업데이트 시간좀 걸리지 않나요 끝났나요 ㅜㅜ 오늘은 못하는건가 ㅠㅠ

**Comment by hanchaoa** [comment]
저만 롤 접속하면 업데이트 실패뜨면서 명시되지 않은 오류가 발생햇다고 뜨나요? 
원레 로그인 하면 접속거부뜨지않나요?ㅠㅠ 답변좀요

**Comment by hanchaoa** [comment]
그냥 전 롤 클린설치중입니다.. ㅠㅠ..

**Comment by mrz1277** [comment]
북미 업데이트 완료되었습니다. 추가 이슈 있으신 분들은 새로운 글로 올려주세요.

**Comment by tjfcksdud** [comment]
죄송한데 혹시 게임내 소환사이름 크기나 스킬을 쓰면 나오는 쿨타임의 초수 글씨크기가 비정상적으로 작은데 원래 크기로 나오게 할수있는 방법이 있을까요?

**Comment by voou1312** [comment]
롤 실행은 됩니다만 추가적으로 올려주신 게임 내 채팅창 글씨가 떨어지는 프로그램으로 게임 실행시 로그인 챔피언 선택 다 되는데 로디엥서 팅기고 접속이 안됩니다 ㅠ

**Comment by ChoiMinJe** [comment]
바이너리 체크섬이 일치되지 않네요 계속 ㅜㅜ

**Comment by mrz1277** [comment]
여긴 lolchatfix 프로그램 문의하는 곳이 아닙니다 ㅜㅜ
http://lolchatfix.funso.me/ 페이지 가보시면 개발자님이 5.18 패치 호환되는 새로운 버전 0.1.3 올려주셨습니다.
