### ISSUE TITLE
업데이트 허용 변경 후 롤 패치중 명시되지 않은 오류 발생

### ISSUE THREAD

**Issue by segunlee** [mrz1277/LoLKR#5]
업데이트 허용변경 후 롤 패치중 명시되지 않은 오류 발생이 되어 패치가 되지 않습니다.
이후 LOL종료 후 업데이트 방지로 변경 후 LOL을 시작하면 정상적으로 패치가 진행됩니다.

사용자 입장에서 업데이트 허용 후 당연히 패치가 정상적으로 이루어진다고 생각하지만 첨부한 이미지와 같이 오류가 발생하며, 이때 다시 업데이트 방지를 설정하면 정상적으로 패치가 이루어 집니다.

항상 감사하게 쓰고 있습니다.

LOL 명지되지 않은 오류 발생 시 Patch Log 링크 첨부합니다.
https://drive.google.com/file/d/0BxsGumTxOKTVdjVfZ2hyNlR1RmM/view?usp=sharing

![2015-04-30 10 20 57](https://cloud.githubusercontent.com/assets/3186834/7413553/be612b5c-ef87-11e4-8fa0-40ed0eb89405.png)

**Comment by msuksong** [comment]
다시 서버를 북미서버로 하고 패치를 한 후, 클라이언트 종료하시고 LoLKR 실행하셔서 다시 '패치 하기'를 하신 다음에 실행해보세요. 저는 그렇게 하니까 되네요.

**Comment by mrz1277** [comment]
로그를 보니 우회 경로가 하나 추가된것 같네요.
`/usr/local/etc/nginx/nginx.conf` 파일에 다음 라인을 끼워넣고 `nginx`를 재시작해보세요.

```
rewrite      ^(.*)_KR$        $1_NA;
rewrite      ^(.*)_ko_kr/(.*)$   $1_en_us/$2;  <<-- 새로 추가된 라인
rewrite      ^(.*)_kr/(.*)$   $1_na/$2;
```

저장하신뒤,

```
nginx -s reload
```

로 nginx 재시작 한 다음 업데이트 테스트 부탁드릴게요~

**Comment by segunlee** [comment]
정상작동 하였습니다. 감사합니다
