### ISSUE TITLE
오늘 패치떳나요?

### ISSUE THREAD

**Issue by hanchaoa** [mrz1277/LoLKR#50]
롤을 들어가보니 업데이트 실패떳어요 그래서 업데이트 허용으로 해놓고 게임 실행시켯는데 파일스캔만되네요.. 방지에 다시두면 업데이트 실패라떠요 
![screen shot 2015-09-22 at 4 32 43 pm](https://cloud.githubusercontent.com/assets/14311302/10015028/b7ace634-6147-11e5-9a28-21ca8e359647.png)

**Comment by mrz1277** [comment]
5.18 이후로 패치는 없는데 계속 같은 증상이라면 조금 불편하시겠지만 롤 클린설치를 권장드립니다.
