### ISSUE TITLE
LoLKR을 깔고

### ISSUE THREAD

**Issue by hyeonseolee** [mrz1277/LoLKR#52]
앱을깔고나서 5.18패치부터 현제 19 패치까지 롤 클라이언트가 전혀 패치를 진행하지못하고 위에 실행만 뜨네요 패치가 적용되지않는데 어떻게 고치죠

**Comment by mrz1277** [comment]
현재 롤 클라이언트 버전이 5.18이라는 말씀이신가요 아님 5.17이라는건가요?

**Comment by statikkyasuo** [comment]
저도 똑같은 현상을 겪고 있는데요 지금 북미롤 한국롤 둘 다 패치버전이 5.19 이고 한국롤의 경우 오늘 새벽에 업데이트가 된 상태입니다 그런데 클라이언트가 5.18에서 5.19로 업데이트를 거부해서 위에 실행 버튼만 뜨는 사태가 벌어지고 있어서 패치가 안되네요 lolkr에서 업데이트 허용을 해놓았는데도 불구하고 이미 업데이트된걸 업데이트 하지 않는 상태입니다. 한마디로 원래 5.19여야 하는데 5.18에서 업데이트가 멈춰 클라이언트의 버전이 낮아서 게임 플레이가 거부된다고 볼 수 있겠네요. 이걸 어떻게 고치죠?

**Comment by hyeonseolee** [comment]
네, 딱 저런 상황입니다. 지금 롤을 다시 받아서 북미버전 패치중이긴한데 빨리 고쳐주셨으면 좋겠네요

**Comment by kafka3323** [comment]
저도 같은상황입니다. 해결방법이 없나요?

**Comment by mrz1277** [comment]
지난 5.18 때와 똑같이 북미보다 한국이 먼저 업데이트가 되서 발생한 문제로 보입니다. http://status.leagueoflegends.com/?en_US#na 페이지 보면 북미섭은 한국시간으로 오늘 오후 6-7시에 업데이트가 된다고 하네요. 그때까지 기다리시거나 그안에 오세아니아 서버로 우회 해서 임시로 접속하는 방법이 있긴한데 수동으로 몇 가지 파일을 조작해 주셔야 합니다.

# 순서
1. 롤 시작화면에서 오세아니아 서버로 바꿉니다. 그러면 오세아니아 서버 업데이트가 진행될 겁니다.
2. 롤을 종료하고 `/Applications/League of Legends.app/Contents/LoL/RADS/projects/lol_air_client_config_kr` 폴더를 지웁니다.
3. `/Applications/LoLKR.app/Contents/Resources` 폴더로 이동합니다.
4. `1_nginx.sh` 파일을 열고 아래 3 부분을 찾아 화살표 오른쪽 부분으로 수정합니다.
   
   ```
   $1_NA; ==> $1_OC1;
   $1_en_us/$2; ==> $1_en_au/$2;
   $1_na/$2; ==> $1_oc1/$2;
   ```
5. `2_download_versions.sh` 파일을 열고 아래 부분들을 모두 수정합니다.
   
   ```
   releaselisting_NA ==> releaselisting_OC1
   lol_air_client_config_na ==> lol_air_client_config_oc1
   ```
6.  `3_lol.sh` 파일을 열고 아래 부분을 수정합니다.
   
   ```
   cp -r "$BASE_DIR/projects/lol_air_client_config_na" "$BASE_DIR/projects/lol_air_client_config_kr"
   ==>
   cp -r "$BASE_DIR/projects/lol_air_client_config_oc1" "$BASE_DIR/projects/lol_air_client_config_kr"
   ```
7. `LoLKR` 앱을 열고 패치하기를 하고 스위치를 허용합니다.
8. 대한민국 서버로 패치를하고 로그인 화면에 들어갔을때 5.19 화면이 나오면 성공입니다.

![screen shot 2015-09-30 at 11 58 23 am](https://cloud.githubusercontent.com/assets/2252863/10183432/90e11b78-676a-11e5-9385-49ad62f186ee.png)

**Comment by taking** [comment]
말씀해주신 부분으로 성공적으로 접속 되었습니다. 
하나만 질문 드려도 될까요? 한국서버와 비슷한 오세아니아 서버를 기준으로 패치를 하는게 아닌 북미 기준인 이유가 있을까요?

**Comment by kafka3323** [comment]
저는 왜 패치실패라고 뜰까요..

**Comment by kafka3323** [comment]
허용한 상태에서 롤을 실행시키면 명시되지않은 로그라고 오류가 뜨는데
방지로 다시 바꾼상태에서 실행하면 잘됩니다.. 이상한건 패치가 저절로 되었다고 해야하나..

**Comment by mrz1277** [comment]
@taking 네 일단 최근 패치때 이런 문제가 발생하기 전까지 오세아니아가 한국과 업데이트 시간이 비슷하다는 사실은 저도 처음 알게 되었습니다. 그리고 롤 공식홈에서도 맥버전 다운받는 페이지에 가면 어느 대륙이든 북미가 기본으로 떠서 디폴트 설정을 따라간 감도 없지 않습니다..(처음부터 다른 대륙 버전으로 dmg 파일 받아보신 경험은 드물겁니다.) 그렇지 않으면 북미 업데이트를 설치하고 오세아니아도 따로 업데이트 해야하니 시간이 배로 들겠죠.

그리고 다른 무엇보다 북미가 한국보다 업데이트가 늦은것은 지난 5.18 때 처음 나타난거라 한국은 항상 다른 대륙보다 업데이트가 늦는것으로 알고 있었던 기존의 경험때문에 굳이 다른 대륙으로 사용할 필요가 없었습니다. 5.18때 비슷한 의견이 있었음에도 불구하고 오세아니아로 변경하지 않았던 이유는 그때가 특이 케이스일 수 있었기 때문에 다음 패치를 한 번 보고 생각해보려는 마음도 있었구요.

아무튼 이번 패치로 북미가 항상 한국보다 빠르다는 전제는 옳지 않는게 되었으니 시간날때 기준 서버를 오세아니아로 바꾸는 작업을 해야겠네요.

**Comment by taking** [comment]
맥을 사용하면서 롤을 한국에서도 편하게 접속 할 수 있도록 LoLKR를 제작해주셔서 정말 감사하게 생각하고 있습니다. :+1: donate 를 만들 생각은 없으신가요? 조금이나마 감사드리고 싶네요. ㅎㅎ

**Comment by mrz1277** [comment]
@taking 말씀만이라도 정말 감사합니다.^^ 

처음 본 프로그램을 개발하게 된 계기가 저도 롤을 아주 즐겨하고 있었고, 비슷한 상황에 있는 유저분들과 공유하고 싶어서 배포하게 된거라 donate 관련해서는 따로 생각해본적은 없었는데.. 그래도 생각해 주신다면.. 저희는 같은 롤 유저니까.. 롤 상점에 있는 선물하기로 혹 간단한 것이라도 보내주신다면 더 기쁜마음으로 감사히 받을수 있을것 같네요 ㅋㅋ 아니면 같이 랭겜(즐겜)하는것도 언제든 환영입니다. 참고로 제 소환사명은 `NEWFUN GUEST` 이니 친추/귓말 주세요.ㅎㅎ

**Comment by ysw8572** [comment]
@mrz1277 저는 Applications 이 어디에 있는지도 잘 모르겠네요 ,,, 터미널에 들어가서 입력하는건 아닌것 같은데 
어떻게 위에 알려주신데로 하나요,,, 맥북을 잘 활용 하지 못해서 쉽게 설명 부탁 드리겠습니다 ㅠㅠ

**Comment by mrz1277** [comment]
@ysw8572 터미널 환경이 익숙하지 않으시면 Finder 에서 Cmd+Shift+O 를 누르면 위 경로를 복사해서 이동할 수 있습니다.

**Comment by ysw8572** [comment]
@mrz1277 불편하실텐데 죄송합니다 ㅜㅠㅠ
Applications 가 있긴있습니다만 롤에 사용되는 폴더는 아닌것 같습니다...ㅠㅠ

**Comment by mrz1277** [comment]
@ysw8572 그럼 파인더에서 기존 롤을 설치한 경로에 가셔서 아이콘을 우클릭하고 패키지 컨텐츠 보기 메뉴를 누르면 탐색할 수 있습니다.

**Comment by ysw8572** [comment]
@mrz1277 감사합니다 ㅠㅠㅠ 컴맹이라서 힘들었는데 ㅠㅠ ㅎㅎ 고맙습니다

**Comment by mrz1277** [comment]
@ysw8572 고생하셨습니다ㅋ

**Comment by mrz1277** [comment]
북미 서버가 업데이트 되었으므로 본 이슈는 닫겠습니다.
