### ISSUE TITLE
오늘 5.20 패치떳는데..

### ISSUE THREAD

**Issue by hanchaoa** [mrz1277/LoLKR#53]
제가 전에 한국서버가 더 빨리 패치되서 개발자님이 알려주신대로 오세아니아서버로 바꾼다음에 한국서버로 강제접속햇는데 오늘 들어가보니까 파일 스캔만 계속되네요 ㅠㅠ.. 다시 뭐 바꿔야하나요?

**Comment by bumjinkm** [comment]
ㅜㅜ저도 같은 문제

**Comment by ChoiMinJe** [comment]
지금 북미로 통해서 한국섭으로 접속하는 방법자체가 뭔가 문제가 있는것 같습니다 ㅜㅜ
5.19부터 이런현상때문에 LOL KR지운상태로도 계속했는데 5.20에서도 그렇내요
맥버전 지원안해주는게 영향이 큰거같습니다. ㅠㅠ

**Comment by mrz1277** [comment]
이전 이슈랑 일단 똑같습니다. 해결방법도 오늘 오후까지 기다리시거나 수동으로 https://github.com/mrz1277/LoLKR/issues/52 중간에 나와있는 방법대로 하셔도 됍니다. 이전에 이 방법으로 해결하셨던 분들은 추가 작업없이 바로 접속 되실겁니다.

**Comment by hanchaoa** [comment]
저는 이전에 저 방법으로 햇엇는데 파일찾는게 10000까지가도 업데이트가 되지 않앗습니다 그래서 롤 클린설치중인데 다음패치에도 그러면 별다른 방법이 없을까요?

**Comment by yong076** [comment]
저도 똑같은 현상 입니다. #52에 나와 있는 것을 적용 해서 사용 해도 업데이트는 되다가 32%에서 멈춰있는 현상(1시간..) 이 생기네요.

**Comment by mrz1277** [comment]
@yong076 혹시 다시 껐다 켜도 동일한가요?

**Comment by hanchaoa** [comment]
오늘 패치내용중에 Mac Load Time Improvements 라는게 생겻네요! 가끔 다른유저분들이 컴퓨터 안좋다고 그러는데 이제 들하겟네요ㅋㅋ..

**Comment by hanchaoa** [comment]
대신답변 죄송한데 전 동일합니다 한 5번정도 껏다 해봐도 안되길레 롤 클린설치중입니다

**Comment by seojh0103** [comment]
![2015-10-14 8 27 45](https://cloud.githubusercontent.com/assets/15123579/10482419/e67d4338-72b2-11e5-881a-dd92a3923601.jpg)
롤 실행시 명시되지 않은 오류라고 나오는게아니라 런처 실행한 화면에서나오는데 이건 어떤문제인가요? 5.20이전 버전에선 이런일이 없었습니다.

**Comment by ysw8572** [comment]
제가 이거 뜨다가 패치를 받고 게임 중 이거든요 
하시는 방법이 
롤 클라이언트 실행 후 한국 서버에서 다른서버로 변경 해주셨다가 다시 한국 서버로 들어와서 패치 받으시면 될껍니다 ㅎㅎ

**Comment by seojh0103** [comment]
그렇게도 해봤는데 다시 한국서버로바꾸면 이 창이 계속뜨내요..

**Comment by mrz1277** [comment]
@seojh0103 업데이트 허용인가요? 기존 `/Applications/League of Legends.app/Contents/LoL/RADS/projects/lol_air_client_config_kr` 지웠다가 롤 끄고 서버 바꾸고 다시 설치해보세요

**Comment by seojh0103** [comment]
@mrz1277 /lol_air_client_config_kr을 지우면 한국서버를 선택할 수 없는데 LoLKR에서 패치하기 이후에 다시 한국서버 패치는 받는건가요?
위와 같이 진행했는데 같은증상이내요..

다른나라 서버들은 문제없이 접속, 패치됩니다

**Comment by hanchaoa** [comment]
죄송한데 이문제는 어떻게해결해요 아까는 5000까지 갓는데 다시 껏다켯어요 패치가 5.20패치가 안되요ㅠㅠ..
![screen shot 2015-10-14 at 8 14 04 pm](https://cloud.githubusercontent.com/assets/14311302/10484621/4d1fbeca-72b0-11e5-9c06-8da712aa0a8f.png)

**Comment by mrz1277** [comment]
@seojh0103 @hanchaoa 님 불편하시겠지만 현재 설치된 롤이랑 LoLKR 둘다 지우고 다시 처음부터 북미판 롤설치하시고 LoLKR도 다시 설치하시는 편이 좋을 것 같습니다ㅜ 현재 북미도 5.20 패치된 상태니까 아마 클린 설치 하시면 문제 없을 겁니다.

**Comment by dylanchoi1** [comment]
개발자는 아니지만 해결방법 올려드립니다.

/Applications/League of Legends.app/Contents/LoL/RADS/projects/

에서 lol_air_client_config_kr폴더를 지우고 lol_air_client_config_na폴더를 복제후 lol_air_client_config_kr이름으로 바꿔줍니다

그리고 releases/0.0.0.54 폴더에 들어가줍니다

그안에 deploy폴더가 있는데 안에 lol.properties파일 북미로 셋팅되어있는데

안에 한글서버로 패치된 lol.properties파일로 수정해줍니다.

재실행하면 업데이트가 제대로되는 화면을 볼수있고 문제가 해결됩니다
