### ISSUE TITLE
패치

### ISSUE THREAD

**Issue by hyeonseolee** [mrz1277/LoLKR#56]
제 컴퓨터에서 LOLKR을 깐뒤에 전혀 패치를못하는데 왜이러죠ㅜㅜ
앱지우고 nginx?그거도 지워봤는데 계속 패치를못해요
롤 지우고 다시깔아봐도 안되는데 어떡하죠

**Comment by mrz1277** [comment]
아래 파일들을 압축해서 올려주세요
1. `/Applications/League of Legends.app/Contents/LoL/Logs/Patcher Logs/` 에서 가장 최근 *_LoLPatcher.log 파일
2. `/Applications/League of Legends.app/Contents/LoL/RADS/system` 폴더
3. 터미널에서 `which nginx`, `ps -ef | grep nginx` 실행 결과 스크린샷

**Comment by hyeonseolee** [comment]
압축파일을 못 올린다는데요

**Comment by mrz1277** [comment]
그럼 구글드라이브나 드롭박스로 공유해주세요

**Comment by hyeonseolee** [comment]
그냥 이메일로 보내드리면 안될까요

**Comment by mrz1277** [comment]
yakiyama@naver.com 으로 보내주세요

**Comment by hyeonseolee** [comment]
보내졌나요

**Comment by mrz1277** [comment]
로그파일을 잘못보내셨네요.

그냥 https://github.com/mrz1277/LoLKR#패치-삭제하기 에서 전부 다 삭제하고 다시 롤 새로 깔고 북미 업데이트를 진행하세요. 그런다음 LoLKR 새로받아서 패치하시면 잘 될겁니다.

**Comment by hyeonseolee** [comment]
전에 그렇게 한번했었는데 다지우고 LoLKR도 안썻는데 또 이러는데요

**Comment by hyeonseolee** [comment]
이거 처음에는 LoLKR을 쓰고 나서부터 패치가 안되더니 북미버전에서 다시 롤깔고 그뒤로 LoLKR앱을 안썼는데도 이러면 LoLKR에 문제가있는거 아닌가요..분명nginx삭제했는데도 안되는거보면 경로변경도중에 뭔가 잘못됬던가 지웠으면 되야정상인건데..

**Comment by mrz1277** [comment]
보내주신 파일들을 보니 업데이트 서버가 정상적인 롤 서버를 가리키고 있고 nginx 가 안깔려 있어서 롤이 다른 패치프로그램으로 조작이 가해지지 않는 상황에선 업데이트가 안 될 이유가 없습니다. 일단 기존 롤 놔두고 다른 이름으로 하나 더 설치해서 LoLKR 패치같은거 하지말고 업데이트 진행해보세요.

**Comment by hyeonseolee** [comment]
북미버전에서 새로받은거 말씀하시는거죠?

**Comment by mrz1277** [comment]
네

**Comment by saw4831** [comment]
이번에 나온 5.21버전도 북미 서버가 먼저 업데이트 되야 한국 서버 업데이트를 할 수 있나요??

**Comment by hyeonseolee** [comment]
일단 기존 롤 혹시몰라서 복구버튼 눌러봤는데 패치가 되는건지 복구중인건진모르겠지만 일단 되긴 되네요 해보고 안되면 다시 알려드리겠습니다

**Comment by mrz1277** [comment]
@saw4831 네 오늘 저녁에 북미도 업데이트 될 예정인데요, https://github.com/mrz1277/LoLKR/issues/52 이 글 중간에 오세아니아 서버로 바꾸는법이 있으니 적용하면 지금 바로 접속 가능하실겁니다.

@hyeonseolee 네

**Comment by saw4831** [comment]
감사합니당

**Comment by hyeonseolee** [comment]
아 아직 북미가 업데이트가 안된건가요?그래서 패치가 안되는 거일 수도 있지않을까요?

**Comment by mrz1277** [comment]
아.. 패치를 못하는게 오류가 있는게 아니라 진행이 안된다는거였나요? 그럼 안되는게 맞아요..

**Comment by hyeonseolee** [comment]
그럼 저는 지금 패치중인게 아니라 복구중인거네요..;

**Comment by hyeonseolee** [comment]
오늘 몇시경 패치가 열릴까요?

**Comment by mrz1277** [comment]
아마도 7시는 지나야 할겁니다.

**Comment by hyeonseolee** [comment]
갑사합니다

**Comment by califoniaroll** [comment]
저는 평소에 하던 대로 방지에서 허용으로 풀고 롤 실행해서 롤 한국섭 5.21 패치를 받고 실행했는데 롤에서는 여전히 제 클라이언트 버전이 5.20이라 뜨네요 ㅠㅠ 어떡하죠?
<img width="1280" alt="screen shot 2015-10-29 at 5 46 47 pm" src="https://cloud.githubusercontent.com/assets/13255715/10813849/26a1f43c-7e65-11e5-81eb-fbaad9d296de.png">
<img width="1280" alt="screen shot 2015-10-29 at 5 47 16 pm" src="https://cloud.githubusercontent.com/assets/13255715/10813857/28d96244-7e65-11e5-8e85-f8a602d8bdc9.png">

**Comment by mrz1277** [comment]
@califoniaroll 북미 업데이트가 아직 안되서 접속이 안됩니다. 위에 코멘트 참고하세요.

본 이슈는 닫겠습니다.
