### ISSUE TITLE
번거롭게 해서 정말 죄송합니다

### ISSUE THREAD

**Issue by califoniaroll** [mrz1277/LoLKR#57]
아까 얼마 전까지 열려있던 이슈에 마지막으로 코멘트 단 사람인데요 그럼 7시쯤에 북미서버가 업데이트 되면 그냥 롤 실행하면 바로 접속이 가능한 건가요?

**Comment by mrz1277** [comment]
아마 추가 업데이트가 있을겁니다.

**Comment by califoniaroll** [comment]
추가 업데이트라는 건 다시 한번 패치를 해줘야 한다는 뜻인가요?

**Comment by mrz1277** [comment]
아뇨 자동으로 진행되는

**Comment by califoniaroll** [comment]
아 그럼 그냥 바로 접속된다는 건가요?

**Comment by mrz1277** [comment]
네

**Comment by califoniaroll** [comment]
네 감사합니다
