### ISSUE TITLE
LoLChatFix

### ISSUE THREAD

**Issue by Hanchhoa** [mrz1277/LoLKR#58]
5.21패치 나오고 저는 현재 플러그인 버전에 0.1.3뜨면서 빨간글씨뜨는데.. ㅠㅠ 제작자님 공식 웹사이트도 막혓는지 들어가지 못하겟더라고요 혹시 롤 설정을 바꿔서 문제를 해결할수 잇을까요?

**Comment by voou1312** [comment]
안녕하세요 개발자님이 개발해주신 프로그램을 잘 애용중인 유저입니다.
프로그램 이용 중 작동이 잘 안될 때 패치를 새로하거나 파란불이 나올 때 까지 껐다 다시 키고 그럽니다.
처음 프로그램을 시동할 땐 터미널로 일러주신 코드를 쓰죠. 

제가 맥 포멧 후 프로그램을 다시 설치하는 도중에 개발자님의 프로그램을 다시 패치하거나 코드를 여러번 입력했을때 용량이 몇십메가정도씩 누를때마다 쌓이는데 이 쌓인 데이터를 지우는 방법 있을까요?

**Comment by mrz1277** [comment]
@Hanchhoa LoLChatFix 는 http://lolchatfix.funso.me/ 이곳에 문의해주시기 바랍니다.

@voou1312 용량이 쌓이는 위치가 정확히 어디인가요?
