### ISSUE TITLE
명시되지않은 오류가 계속 뜹니다.

### ISSUE THREAD

**Issue by k9imJ** [mrz1277/LoLKR#59]
nginx 터미널에서 언인스톨하고 재설치해도 뜹니다.

https://github.com/mrz1277/LoLKR/issues/42

여기를 참고 했었습니다.

처음 부터 저는 초록 불이 들어오기는 합니다.
2달 전에는 정상적으로 플레이 한적있었고, 그 때부터 되지않아 지우고 재설치 한게 지금입니다.

<img width="363" alt="skitch" src="https://cloud.githubusercontent.com/assets/15539550/10867982/7c9ac71a-80c2-11e5-99c6-efe675c50fbc.png">

<img width="1286" alt="pskitch" src="https://cloud.githubusercontent.com/assets/15539550/10867991/e15fac10-80c2-11e5-8d1c-8da79f46b2de.png">
as you know 이런 메세지가 뜨고요

로그는 첨부하도록 하겠습니다.
https://drive.google.com/file/d/0B-3oa1TnfXvMY252WU5Tc1hmUzQ/view?usp=sharing

멋진프로그램과 도움을 주셔서 감사합니다.

**Comment by mrz1277** [comment]
확인이 좀 늦었습니다.
아직도 동일한 증상이신가요?

**Comment by k9imJ** [comment]
YES, Im sorry to cant to send in korean.

what should i do?

GREEN keep lighting, but cant connet sever.

**Comment by park4950** [comment]
비슷한 증상입니다. 5.21패치까지 문제 없이 진행했고 패치 후에도 정상적으로 플레이 했었는데 갑자기 그저깨부터 롤 런처를 실행하면 바로 '명시되지 않은 오류가 발생했습니다'라고 뜹니다. 실행창도 아예 안떠요.. 재설치 해야 하나요..?

**Comment by mrz1277** [comment]
@park4950 님은 nginx 가 실행중인지 확인해 주시고 

@k9imJ 님은 `/usr/local/var/www/release` 폴더를 압축해서 보내주시면 제가 한번 확인해보겠습니다.

**Comment by ghost** [comment]
업데이트를 허용하고 북미로 바꾼 후 업데이트를 진행 후,  다시 한국서버로 바꾸고 업데이트를 차단하니 사용 가능합니다.
