### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by dongkurr** [mrz1277/LoLKR#60]
수고하십니다!
다름이아니고 롤 패치를 마치고 터미널로 명령어 입력해서 다운로드? 같은것도 하나 받았는데
계속 터미널에 다음음 커맨드를 복사하여 brew를 먼저 설치해 주세요. 라고 나옵니다
그리고 롤은 그냥 실행해보려고 했더니 명시할 수 없는 오류가 떳다고 나오고요...

**Comment by mrz1277** [comment]
_터미널로 명령어 입력해서 다운로드? 같은것도 하나 받았는데_
==> 어떤 명령어를 입력했는지 적어주세요.

_계속 터미널에 다음음 커맨드를 복사하여 brew를 먼저 설치해 주세요. 라고 나옵니다_
==> 터미널 화면을 캡쳐해서 올려주세요.

**Comment by dongkurr** [comment]
터미널로 명령어 입력해서 다운로드? 같은것도 하나 받았는데
==> ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
계속 터미널에 다음음 커맨드를 복사하여 brew를 먼저 설치해 주세요. 라고 나옵니다
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Last login: Mon Nov  9 12:45:31 on ttys000
dong-gyuui-MacBook-Pro:~ dong-gyugim$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1
==> The following directories will be made group writable:
/usr/local/.
==> The following directories will have their owner set to dong-gyugim:
/usr/local/.
==> The following directories will have their group set to admin:
/usr/local/.

Press RETURN to continue or any other key to abort

**Comment by mrz1277** [comment]
`Press RETURN to continue or any other key to abort`

메세지가 나오면 Return(엔터)키를 누르세요

**Comment by dongkurr** [comment]
네 지금 패치 진행중입니다!
근데 롤 패치도 같이하고 있는데 원래 이렇게 오래걸리나요?..

**Comment by dongkurr** [comment]
현재 lolkr 은 설명해주신 방법으로 설치하여 초록 불이 들어오고 있는 상황이구요!!
근데 롤 런쳐를 실행하면 로고는 나오는데 실행이 안되고 꺼지는 현상이 발생중입니다..ㅠ

**Comment by dongkurr** [comment]
롤 런쳐도 켜졌습니다!!!
그런데 한국 서버로 바뀌지 않습니다 ㅠㅠ
