### ISSUE TITLE
업데이트가 안되요

### ISSUE THREAD

**Issue by Penumono** [mrz1277/LoLKR#61]
안녕하세요 LOLKR을 쓰고있는 한 맥북 유저입니다
다름이 아니고 LOLKR에 오류가 있는거같아 글을 써봅니다.
저번에 롤 새로운 버전이 나왔을때 업데이트를 할려고 LOLKR에서 한국서버 업데이트를 북미로 돌렸습니다.
LOLKR에서는 성공적으로 적용이 됬다고 했는데 런쳐를 키니까 “게임 시작” 이 바로 뜨더군요
아니나 다를까, 버전이 업데이트가 안되있었습니다.
그래서 롤을 지우고 다시 깔았습니다 근데 지금 최근에 나온 5.22 버전도 지금 업데이트가 안되더군요
이 오류를 고칠수 있는방법은 없는지 해결방법을 보내주시면 감사하겠습니다.

**Comment by mrz1277** [comment]
공지 상단에 글을 업데이트 했으니 확인해 주세요.
