### ISSUE TITLE
LOL KR을 와전히 삭제하고 싶습니다

### ISSUE THREAD

**Issue by SeokhyunSeo** [mrz1277/LoLKR#63]
제가 이 프로그램을 다운받고 새로운 버전이 나올때마다 패치가 안되어 롤을 다시 다운받아야 하는 일이 생겼습니다. 그래서 저는 이 프로그램을 삭제하였는데 이번 패치때 또다시 패치가 안되는 오류가 있었습니다. 어떻게 하면 프로그램을 삭제할 수 있을까요?

**Comment by mrz1277** [comment]
공지 상단에 글을 업데이트 했으니 확인해 주세요. 패치 삭제에 관한 내용은 글 하단에 있습니다.
