### ISSUE TITLE
혹시 수정된 파일을 받을 수 있을까요?

### ISSUE THREAD

**Issue by ombombo** [mrz1277/LoLKR#64]
/Applications/LoLKR.app/Contents/Resources

여기에서 3 파일을 수정하라고 하셨는데

수정된 파일을 업로드 해주실 수가 있을까요?

편의를 위해 대치를 이용하다 얽혀서 틀어졌어요

혹시 업로드 가능하신가요? 붙여넣기 하고 싶습니다 ㅠㅠ

**Comment by mrz1277** [comment]
파일 업로드가 안되서 본문 설명 옆에 파일 내용 전문이 담긴 링크 추가했습니다. 텍스트 편집기로 작업하셔서 저장하셔도 되고 아니면 LoLKR 앱을 다시 받으셔서 수정해도 될것같습니다.
