### ISSUE TITLE
전 뭐가 문제일까요?

### ISSUE THREAD

**Issue by bocfish** [mrz1277/LoLKR#65]
북미지역에 살고있다가 한국으로 넘어왔습니다.
한국에서 롤을 즐기려고 알아보던중 lolkr에 대해 알게되어 시작되었는데
언제부턴진 몰라도 자꾸 에러가 생기네요..
여기 이슈에 올라오는 모든 에러가 저에게 발생한답니다 ㅎㅎ

얼마전부터 오세아니아 섭이 먼저 패치가 된다고해서 알려주신 방법대로 해봤지만 안되어서
항상 북미패치기다려서 패치하고 플레이 해왔는데요. 오늘도 그렇게 해야되나 봅니다.

도저히 뭐가 문젠지 모르겠지만 lolkr앱 수정하는 과정에서 뭔가 저랑 다른게 있더라구요.
1_nginx.sh 여기서 텍스트편집기로 편집할 때,
$1_en_us/$2 이렇게 표기되어있는게 아니고 저는 $1_en_us/\$2 이렇게 슬러시(/)하나가 추가되어있네요
$1_na/\$2; 이 부분도 이렇게 되어있는데

바꾸시라고 하신대로 $1_en_au/$2; 이렇게도 바꿔보고 $1_en_au/\$2;  이렇게도 바꿔봤지만, 패치는 항상 되지않습니다.. 

바쁘시더라도 제 문제점에 대해 알려주시면 감사하겠습니다.

참고로 os는 el capitan으로 업그레이드했고 macbook pro mid 2015입니다 감사합니다.

**Comment by mrz1277** [comment]
죄송합니다. 말씀하신대로 '$' 앞에 역슬래시()가 빠져있었네요. 방금 다시 본문 수정했습니다. ㅠㅠ
