### ISSUE TITLE
상단 공지 글 확인하고 여쭤봅니다!

### ISSUE THREAD

**Issue by dongkurr** [mrz1277/LoLKR#67]
3번까지는 무사히 진행했는데, 4번에 1_nginx.sh 파일이 어딨는지 모르겠습니다ㅠㅠ

**Comment by mrz1277** [comment]
LoLKR 앱을 오른쪽 버튼 눌러서 패키지 내용보기를 누르세요

**Comment by dongkurr** [comment]
감사합니다!
