### ISSUE TITLE
 LoLKR is not working 

### ISSUE THREAD

**Issue by ghost** [mrz1277/LoLKR#7]
메일로도 방금 문의 드렸던 부분입니다!
혹시 메일 확인 못하실까봐 이슈에 한번더 올립니다

깃허브에 나와있는대로 brew를 설치한 후에 LoLKR.app을 실행하고 패치에 들어갔는데
자꾸 nginx가 설치 안됬다고 오류를 뿜더군요 그래서 brew를 통해서 nginx를 따로 설치해주고

루트 권한으로 /usr/local/etc/nginx/nginx.conf 파일을 깃허브에 나와있는대로 복사 붙여넣기 하고
저장후에 LoLKR.app 패치 들어가서 "이미 설치하였음으로 설치하지 않겠습니다"에 체크하고 패치를 진행했는데

2_download_version.sh만 출력되고 아무 일도 일어나지 않네요

안되서 마지막으로 LoLKR.app 파일 속의 sh 스크립트를 하나씩 다 입력해주었는데
마지막에서 정상적으로 work가 되지않아 문의해봅니다!
![screen shot 2015-05-16 at 1 16 33 am](https://cloud.githubusercontent.com/assets/9894346/7657582/092abe68-fb6e-11e4-9b28-8e123bd0a584.png)

**Comment by mrz1277** [comment]
일단 현재 업데이트 기간에 패치를 하셨으니 한국섭에 접속은 안되실 겁니다. 다음 패치부터 정상적으로 되실거에요.
수동으로 스크립트 실행하실때 정상적으로 실행되지 않은 sh 파일이 어떤건가요? 파라미터는 어떻게 입력하셨는지, 스크립트 실행후 다른 메세지 출력은 없었는지도 확인해주세요.

**Comment by ghost** [comment]
아. 제가 잘못썼네요 sh파일이 정상적으로 실행되지 않은게 아닙니다.
sh파일을 에디터로 열어서 나와있는 스크립트대로 한줄한줄 써줬었는데
스크립트 보면 $1가 롤 파일 경로를 뜻하는거같은데 오픈이 안되더라고요.
어떻게 설정해줘야하는지도 잘모르겠어서.. 마지막 3번째 lol.sh에서 막혔습니다

nginx.sh와 download_versions.sh 까지 모든 스크립트 입력해주었을때 출력되는 다른 메세지는 없었습니다.

**Comment by mrz1277** [comment]
각 스크립트 파일 상단의 주석을 보면 실행 예제 커맨드가 나와있습니다.
3_lol.sh 파일은 터미널에서 아래와 같이 전달인자를 넘겨주면 됩니다.
(방금 확인해보니 예제 커맨드 롤 경로에 미스스펠이 있어서 수정했습니다.)

```
./3_lol.sh "/Applications/League of Legends.app" 8010
```

첫번째 인자는 롤 설치경로고, 두번째는 업데이트 방지 포트번호 입니다. 위 커맨드로 에러가 나면 다시 알려주세요.

**Comment by ghost** [comment]
아 위에 주석이있었군요!

해결했습니다 감사합니다 ㅎㅎ

**Comment by mrz1277** [comment]
다행입니다 :)
