### ISSUE TITLE
LoLKR이 아닌 다른 개인적인 질문 드려도될까요?

### ISSUE THREAD

**Issue by ghost** [mrz1277/LoLKR#8]
리눅스, 윈도우환경에서만 개발하다가 맥북을 사고 맥 플랫폼에서 개발을 해보고싶단 생각이들었는데

모르는게 많아서 궁금한 점이 많습니다! 주변에 맥 플랫폼에서 개발하시는분들도 없고 해서

질문드리고싶은데 혹시 괜찮으신가요?

**Comment by mrz1277** [comment]
mrz1277@gmail.com 으로 메일주세요 :)
