### ISSUE TITLE
패치후 오류 질문

### ISSUE THREAD

**Issue by ghost** [mrz1277/LoLKR#9]
1_nginx.sh

/usr/local/bin/brew is /usr/local/bin/brew

Already up-to-date.

==> Installing nginx dependency: openssl

==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.yosemite.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2a-1.yosemite.bottle.1.tar.gz

==> Pouring openssl-1.0.2a-1.yosemite.bottle.1.tar.gz

nginx가 설치되지 않았습니다.

brew정상적으로 설치후에 나와있는 가이드라인대로 설치했는데 
이와같은 오류가 뜨면서 설치가 중단되네요.

그리고 더 하나 질문이 있습니다

![screen shot 2015-05-16 at 1 51 58 pm](https://cloud.githubusercontent.com/assets/12469176/7664775/c392197c-fbd2-11e4-8985-362d4f86d886.png)

 nginx오류때문에 좀 전에 삭제했는데도 nginx에 초록색 불이 들어와있습니다
 해결 방법좀 부탁드려요!

**Comment by mrz1277** [comment]
일단 수동으로 nginx를 다시 설치해보셔야 겠습니다. 터미널에서

```
brew install nginx
```

입력하시고 중간에 혹시 권한을 요청하면 패스워드 입력해주시면 되고요,
그리고 나서 다시 패치하기를 해보시길 바랍니다.

그리고 초록색 불은 앱을 시작하면서 체크하는거라 앱이 켜진 상태에서 nginx 를 지워도 켜져 있을 수 있습니다.
앱을 다시 껏다 켰는데도 초록색 불이 들어왔다면 현재 nginx 프로세스가 실행중이라는 의미입니다.
nginx가 켜져있는지 확인하는 방법은 터미널에서 아래 커맨드를 입력해보시면 됩니다.

```
ps -ef | grep nginx
```

실행했을때 `nginx: master process` 나 `nginx: worker process` 가 출력된다면 현재 nginx가 해당경로에서 실행중이라는 의미입니다. 참고로 nginx를 종료하는 명령어는 다음과 같습니다.

```
nginx -s stop
```

이렇게 하고 다시 `ps -ef | grep nginx` 로 프로세스가 실행중인지 확인하시고 다시 `LoLKR` 앱을 실행하셔서 불이 켜져있는지 확인해보세요.

**Comment by ghost** [comment]
brew를 설치했을때 brew doctor을 하고나니 오류가 많이 뜨길래
2시간에 걸쳐서 겨우 모두 해결하고 brew 로 nginx 설치후에 패치하고 설정다 해줬더니 성공적으로 됬네요!

nginx가 안켜지길래 오류 로그 봤더니 퍼미션 문제였네요 -_-
sudo nginx하고 정상적으로 실행 마쳤습니다

근데 한가지 궁금한점이 저는 북미 패치가 이미 완료된 뒤에 LoLKR를 설치한거라서

클라이언트 들어가서 로그인하면 클라이언트 버전때문에 거부되야 정상인데
왜 비밀번호가 맞지않다고 뜨는걸까요? 아마 북미 클라이언트로 접속된거같은데

어떻게하면 바꿀수있죠? 깃허브보면 북미서버랑 한국서버 클라이언트 번갈아가면서 접속하던데 어떻게한건가요?

**Comment by mrz1277** [comment]
롤 실행하면 오른쪽 상단에 Online이라고 파란 글씨 아래 서버명이 있을겁니다. 누르면 목록나오는데 거기서 Korea선택 하고 언어 선택하시면 됩니다.

**Comment by iwannaplay** [comment]
저는 한국 서버도 5.9 로 되어있습니다. 올려주신대로 했는데 왜 저는 한글서버까지 5.9로 접속이 될까요??
북미서버, 한국서버 왔다갔다 하고, 패치도 다 해보았지만 여전히 한국서버도 5.9로 되어있습니다..

**Comment by mrz1277** [comment]
@iwannaplay 롤 5.9 업데이트 후에 `LoLKR` 앱으로 패치하면 안됩니다. 5.8버전에서 `LoLKR` 앱을 이용해서 자동 업데이트 방지를 미리 해둬야 합니다.

**Comment by mrz1277** [comment]
@r00p3r 님 일단 이 이슈는 닫도록 하겠습니다. 서버 선택이 아직 안된다면 다시 열어주세요.
