### ISSUE TITLE
정말 죄송합니다.. 도와주세요 

### ISSUE THREAD

**Issue by ghost** [mrz1277/LoLKR#98]
앙

**Comment by rimichoi** [comment]
한글패치는 안되고요. LoLKR을 실행하고 nginx 초록불확인하고 허용으로 옮기고 /Applications/League of Legends.app/Contents/LoL/RADS/system 의 locale.cfg 의 언어를 en_AU로 변경하고 게임실행하시면 됩니다.

**Comment by Hanchoa** [comment]
asd
