### ISSUE TITLE
신규 클라이언트는 어떻게 해야하죠? (알파클라이언트)

### ISSUE THREAD

**Issue by haso-ka** [mrz1277/LoLKR#99]
신규 클라이언트를 설치하려 했는데 명시되지 않은 오류가 떠서 오세아니아 서버에서 다시 런처를 다운 받아 신규 클라이언트를 설치 완료했습니다. 그러나 한글패치가 되지 않더군요.
어떻게 시스템파일을 건드려서 한국서버로 접속은 되게 하였으나, 계속 필수 업데이트를 설치해야 한다면서 재실행 되더군요. 근데 업데이트는 서버문제로 되지 않습니다. 업데이트 서버를 따로 건드려야 하는 모양입니다.
도와주세요!

**Comment by rimichoi** [comment]
한글패치는 안되고요. LoLKR을 실행하고 nginx 초록불확인하고 허용으로 옮기고 /Applications/League of Legends.app/Contents/LoL/RADS/system 의 locale.cfg 의 언어를 en_AU로 변경하고 게임실행하시면 됩니다.
